### ISSUE TITLE
php artisan key:generate erreur

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#118]
Raspbian GNU/Linux 11 (bullseye)
PHP 8.2.1 (cli) (built: Jan  7 2023 08:34:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.1, Copyright (c), by Zend Technologies

erreur à la dernière commande:
pi@raspberrypi:/var/www/phpip $ cp .env.example .env 
pi@raspberrypi:/var/www/phpip $ php artisan key:generate
The environment file is invalid!
Failed to parse dotenv file. Encountered unexpected whitespace at [<Consumer Key>].

Cela fonctionne en commentant les deux lignes suivantes, mais je ne sais pas si c'est la bonne solution:
#OPS_APP_KEY=<Consumer Key>
#OPS_SECRET=<Consumer Secret Key>

Merci

**Comment by jjdejong** [comment]
Right, the exemplary values for these keys were incorrectly formatted. Fixed in the last commit #1499100
