### ISSUE TITLE
[question] what is the use of field 'rate' 

### ISSUE THREAD

**Issue by mdkbdg** [jjdejong/phpip#125]
Hi, 
thank you for this project. I am very new on the business process side, please go easy. 
This is not exactly an issue, but a question.

The database table `matter_actor_lnk` has `rate` column. Its default value is 100. How is this field being used? 

I am exploring on how a matter (say, agreement) can be tracked financially. For example, in terms of royalty payment (by milestone, annually, manually, etc). I was thinking of reminder for collection (maybe similar to renewal?) but it comes with 3 major differences: 
a. royalty is disbursed to licensees (of different roles)
b. royalty can be a fixed number or percentage. If it is percentage, it must be based on another number (sales / profit / etc)
c. royalty of actor A can be different with actor B

Please understand that I am not requesting a feature or demanding enhancement. I am just asking for advise if the `rate` column is one possible field to utilise for above need. Otherwise, what would be your suggestion in terms of software design that fit this project?

**Comment by jjdejong** [comment]
The "rate" column was meant essentially to attribute an ownership rate to each of multiple owners, for instance to determine what to bill each owner, or what share of royalty goes to each owner. It is just informative and not used in any calculations. Some companies also want to track inventorship rates between multiple inventors, for instance for determining inventor bonuses.

Apparently the renewal system looks more adequate for your purposes, with some adaptation. Also note that the tasks have cost, fee and currency columns, so you could configure rules that produce a "collect license" task with given (fixed) values for those columns. Unfortunately the task rule system is not based on the actor roles.

**Comment by papoteur-mga** [comment]
>  c. royalty of actor A can be different with actor B

Hello,
I would suggest in this to have a matter for each actor, because there is probably an agreement for each actor, with its own signature date and perhaps each own term.
