### ISSUE TITLE
Error in renewal management tool

### ISSUE THREAD

**Issue by clairey69** [jjdejong/phpip#130]
Hi !

I have a "something went wrong" message when I try to send a "call email" or "reminders" from the "manage renewals" page.

I went to the ftp, config/renewal.php, and checked that "mail_recipient" is set to "client". It is. I changed it to "user", just in case. I still got the same message.

I don't understand the problem.

Thank you in advance !

**Comment by jjdejong** [comment]
You need to setup your external mail server in the `.env` configuration file. See [wiki](https://github.com/jjdejong/phpip/wiki/Renewal-Management#email-templates).
