### ISSUE TITLE
Creating the phpip user doesnt work in Ubuntu for Arm

### ISSUE THREAD

**Issue by jjdejong** [jjdejong/phpip#132]
Hi,
Should I ask questions about the installation instructions here, or file a bug report directly ?

For background, I tried installing phpip onto a Raspberry Pi4 with 8Mb RAM with Ubuntu 22.04 Desktop for that Arm architecture. 
The installation sequence fails initially at the mysql setup, when the following DDL instruction, as provided on the wiki is executed:

"CREATE USER phpip@localhost IDENTIFIED BY 'phpip';"

When I execute the above instruction, I get an error message that it doesn't respect the default encryption required by the mysql server version.

Should I file a bug against the documentation ?

_Originally posted by @iplaw67 in https://github.com/jjdejong/phpip/discussions/127#discussioncomment-9700162_

**Comment by jjdejong** [comment]
Please provide the exact error message.

**Comment by iplaw67** [comment]
Mysql server 8.0.36-ubuntu.22.04.1
Protocol version 10

Error 1819 (HY000): Your password does not satisfy the current policy requirements.

**Comment by iplaw67** [comment]
Seems like the reason is that the default mysql server provided in 22.04 for the Pi is configured with a validate password policy level set to medium:

https://www.tecmint.com/fix-mysql-error-1819-hy000/#:~:text=To%20resolve%20the%20MySQL%20ERROR,the%20password%20validation%20policy%20level.

**Comment by iplaw67** [comment]
This requires the default phpip password to have:

- at least 8 characters;
- one of which must be an upper case letter;
- one of which must be a number;
- one of which must be a special character.

**Comment by jjdejong** [comment]
Well, you answered your own question. Just change `IDENTIFIED BY 'phpip'` to a password that satisfies the policy (a password you will need to change in the `.env` file too). I'll change the install files to include a stronger default password. Strange, because the Ubuntu distributions for x86 don't have MySQL set up with that policy...
