### ISSUE TITLE
Email template sorting

### ISSUE THREAD

**Issue by jjdejong** [jjdejong/phpip#133]
Hello !
When I go to "email templates", they are displayed alphabetically. But when I send an email from a matter, the list of templates are displayed by date of creation (which means they are all mixed up). Would it be possible to set an alphabetical order when we want to send an email ?
Thank you !

_Originally posted by @clairey69 in https://github.com/jjdejong/phpip/discussions/127#discussioncomment-9974018_

**Comment by papoteur-mga** [comment]
@clairey69 Are the filters working? Not in my branch.
