### ISSUE TITLE
Affichage famille pas intuitif

### ISSUE THREAD

**Issue by mchaves13** [jjdejong/phpip#15]
L'affichage d'une famille lors d'une recherche fait redescendre les titres par ordre de création de la plus récente à la plus ancienne - le dépôt prioritaire se retrouve tout en bas
Un affichage par date de création de la plus ancienne à la plus récente serait plus intuitif, ou à tout le moins la possibilité de gérer son affichage avec un bouton "sort by"

**Comment by jjdejong** [comment]
Il suffit de cliquer sur "Reference" pour refaire le tri.
