### ISSUE TITLE
Affichage All Matters - par date de création de la fiche

### ISSUE THREAD

**Issue by mchaves13** [jjdejong/phpip#16]
L'affichage se fait du dossier dernièrement créé au plus ancien, et non en liste de la famille la plus ancienne à la plus récente. 
On se retrouve donc avec un affichage non pas par famille mais par date de création, qui n'a pas de réelle logique au quotidien.

**Comment by jjdejong** [comment]
Cette fonctionnalité a été conçue exprès, pour qu'on voie en premier les derniers dossiers créés (qui sont en principe les plus "chauds"). Pour voir les dossiers dans l'ordre des références, il suffit de de cliquer sur "Reference". Un deuxième clic trie dans l'ordre inverse.
