### ISSUE TITLE
New event - le champ "number" ne redescent pas dans les tâches

### ISSUE THREAD

**Issue by mchaves13** [jjdejong/phpip#17]
Lors de la création d'un événement, exemple "examiner action", "communication" il y a la possibilité de préciser OA1, OA2, R19.1, etc.
Ce numéro redescendait dans la précédente version dans les tâches : Respond : Communication R19.1
Cette fonction est très utile au quotidien

**Comment by jjdejong** [comment]
phpIP n'offre pas cette fonctionnalité. En fait, il s'agissait de l’auto-complétion offerte par le navigateur ! Il faut faire quelques saisies pour que le navigateur réapprenne les valeurs les plus utilisées.
