### ISSUE TITLE
recherche avec une référence "complexe"

### ISSUE THREAD

**Issue by Omnipat** [jjdejong/phpip#18]
lors de la recherche d'un dossier particulier d'une famille de brevets, si on souhaite préciser le code pays ex. 500351MX, la recherche ne donne aucun résultat
la recherche n'est donc possible que sur la famille

**Comment by papoteur-mga** [comment]
La recherche est maintenant possible sur le numéro suivi du suffixe, à savoir le pays, l'origine puis l'indice.
Par exemple, pour filtrer sur les Etats-Unis, on peut saisir "%US"
