### ISSUE TITLE
Edit actors - Create new actor not proposed anymore

### ISSUE THREAD

**Issue by Omnipat** [jjdejong/phpip#21]

**Comment by papoteur-mga** [comment]
Hello,
It is still possible, as seen in this screen shot. When selected, the actor card is created. You have to edit it later if you need.
![Create actor](https://user-images.githubusercontent.com/5154580/68391120-28716200-0167-11ea-9eab-5890216da55b.jpg)

**Comment by jjdejong** [comment]
The issue is when editing the actor detail, in changing the name of an existing linked actor

**Comment by jjdejong** [comment]
This is not really a bug, but a feature request.
