### ISSUE TITLE
Page expired

### ISSUE THREAD

**Issue by papoteur-mga** [jjdejong/phpip#24]
Some requests fails with 419 code, page expired, after a delay without activity.
For example, for the search field for a matter.
This is also the case when updating a field, except that the update fails silently (Events, Tasks, Titles...).
All come back well after refreshing the page.
I think this is because the CRSF token expired, or something like that.
We need at least better messages about what fails, or sync this delay with the login delay.

**Comment by jjdejong** [comment]
The CSRF token mismatch error happens when the web server is restarted and the page is not refreshed, which obviously occurs pretty often during development. We have not experienced the error in production here.

**Comment by jjdejong** [comment]
Just remember to refresh a page that has stayed open for a while before using it.
