### ISSUE TITLE
Editing the filing date is not possible

### ISSUE THREAD

**Issue by papoteur-mga** [jjdejong/phpip#27]
In events frame, I try to edit the filing date, because I mistyping the year.
In edition mode, I can modify the day or the month, but for the year, the edition is stored before I finish to type the 4 digits. Thus, I get 20 and the last digits are lost.
The date picker is of no help, because it is set to 20, and jumping to more than 2000 needs 2000 clicks.

**Comment by jjdejong** [comment]
This is the operation of the browser's datepicker, not of phpIP... Maybe a bug in the current version of FireFox

**Comment by jjdejong** [comment]
Update to FireFox 60.0.3 or above

**Comment by jjdejong** [comment]
The issue remains, and for all date fields. Apparently due to focus switching caused by the browser's date picker

**Comment by jjdejong** [comment]
With the browser's date picker, each manually typed digit fires the "change" event. This defeats the in-place editing functionality

**Comment by jjdejong** [comment]
I plan to remove the date picker. It appears that most dates are entered manually anyway. The issue will be to handle date format internationalization
