### ISSUE TITLE
demande divionnaire, date de dépôt et calcul des annuités

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#29]
Bonjour ,
lorsqu'on souhaite saisir une demande divisionnaire (d'une demande parente), faut-il utiliser l'évènement "file" ?
En effet, cela génère des événements d'annuité à payer le mois de dépôt (et non pas le mois de dépôt de la demande parente).
Merci

**Comment by jjdejong** [comment]
Il faut surtout saisir une demande divisionnaire comme un enfant de la demande mère ("Create child" sur la demande mère), et cocher "Parent application" dans "Use current application as".
