### ISSUE TITLE
Cannot add Priority Claim to patent

### ISSUE THREAD

**Issue by superlou** [jjdejong/phpip#33]
I can add the published, granted, and expiry dates and numbers to a matter with no problem, When I try to add a "Priority Claim" event to record the application number, there is no error shown, but the events list is not updated with the new event. There are no errors shown in the application or in the log file.

Edit: it looks like it has something to do with the date. I can add a priority claim of 1/1/2019, but I can't change it afterwards.

**Comment by superlou** [comment]
I'm not sure if it's related, but if I try to manually update the event in the database via `UPDATE `event` SET `event_date` = '2013-12-23' WHERE `event`.`id` = 23 `, I receive:

```
#1267 - Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
```

The collation type of the `event` table is `utf8mb4_unicode_ci` which makes sense for a multilingual application.

**Comment by jjdejong** [comment]
I can't reproduce that. Can you tell us exactly how you fill in the fields for the new priority claim event? Note that if you use the "Refers to" field, it is the filing date of the referred matter that is used as the priority date, if the referred matter has a filing event. The referred matter date prevails over the date you enter manually.

What locale are you using? What happens if you try 25/01/2019 and 01/25/2019?

**Comment by superlou** [comment]
It seems like a US locale since the prompt is for MM/DD/YYYY, and it won't let me enter "25/01/2019." Is locale set via `.env`? I don't see a key for it. I haven't tried using the refers to field yet.

![image](https://user-images.githubusercontent.com/709695/69983910-d1f90880-1505-11ea-86f8-c4a4429dd03d.png)

I'm trying to enter the date through the GUI as shown above, though it's hard to get a screenshot of it in progress because every one or two seconds the entered date reverts back to 1/1/19. There are no errors listed in the JavaScript console.

**Comment by jjdejong** [comment]
The locale is set to "fr" in config/app.php. But in fact that shouldn't matter, because the date picker normally converts to iso (YYYY-MM-DD) as required by the database. Wrong route.

We've gone astray - what is the remaining issue?

**Comment by superlou** [comment]
Agreed. I can see that the database looks like the right format (though I haven't figured out the collation thing).

I wasn't able to add a "Priority Claim" event with the date 12/25/2013. Just to experiment, I found I was able to add 1/1/2019, but now it cannot be edited or deleted.

**Comment by jjdejong** [comment]
The date cannot be deleted because it's required. If you can't edit it, it could be you have something in "Refers to" that forces the date (normally this field contains the priority application and is automatically filled when you create a new case with "New child"). Otherwise try looking at your browser's console messages - are errors returned? The collation issue?

**Comment by superlou** [comment]
There are no errors in the browser console. As shown above, the "refers to" field is empty, and I double clicked to check that there was no space characters there and I can see in the database that the "detail" field is NULL.

The collation issue is https://github.com/jjdejong/phpip/issues/33#issuecomment-560419746, where I tried to manually set the date in the database.

**Comment by superlou** [comment]
I can see that all my table collations are `utf8_general_ci`:

![image](https://user-images.githubusercontent.com/709695/69986015-70876880-150a-11ea-826e-91cb77449bee.png)

That's weird though, since I can see from `show table status like 'event'` that collation is `utf8mb4_unicode_ci`.

Edit: after setting the database, all tables, and all columns to `utf8mb4_unicode_ci`, I still have the problem editing in the GUI and from the SQL statement, so maybe that's a red herring.

**Comment by jjdejong** [comment]
I have everything in utf8_general_ci (schema, tables, columns), and that was by default, since the creation scripts didn't have the collation specified. What version db are you running?

**Comment by superlou** [comment]
My XAMP stack has:

    Server: 127.0.0.1 via TCP/IP
    Server type: MariaDB
    Server connection: SSL is not being used Documentation
    Server version: 10.4.8-MariaDB - mariadb.org binary distribution
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8mb4)

I actually thought utf8mb4_unicode_ci was intentional since `unicode` does more accurate sorting than `general` in a multilingual environment.

**Comment by jjdejong** [comment]
Nothing was intentional, I don't really master the collation subject...
Anyway the collation issue does not seem to appear when you use the UI, but you cannot set/edit the date as you wish. 
What are the parameters and response of the `PUT` request on the console when you change the date?
What about the other date fields?

**Comment by superlou** [comment]
I can see in the network traffic that when I try to change the date, I get back a 500 error with:

```
{
    "message": "SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `event` set `event_date` = 2019-05-01, `event`.`updated_at` = 2019-12-02 20:34:49 where `id` = 23)",
    "exception": "Illuminate\\Database\\QueryException",
    "file": "C:\\_projects\\phpip\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php",
    "line": 665,
    "trace": [
        {
```

So it does seem like it's something to do with unicode vs. general.

Edit: it's just really odd that this happens with the priority claim but not the grant.

**Comment by jjdejong** [comment]
What is stranger is that the query involves only non-string columns that do not have a collation. It could be that a trigger on the event table is causing the error - what collations are the triggers?

My database actually has a default collation `utf8mb4_0900_ai_ci` and the triggers on the event table have a mix of unicode and 0900. Don't know why, but things work.

**Comment by superlou** [comment]
It was really bizarre. I tried changing everything to the same collation, but still couldn't even run an SQL operation to delete certain records. I wonder if maybe fields were already encoded, and I wasn't running the write operation to change the data itself?

I dropped and recreated the DB, this time explicitly choosing `utf8mb4_unicode_ci` rather than `utf8mb4_general_ci`, and it seems to be working. I can now add an arbitrary Priority Claim date, and some other features seem to be working that I thought I was just using wrong, e.g. New Child.

The only point of weirdness is that I'm not sure how to delete a Priority Claim altogether, but that might be a UI thing.

I'm going to tentatively close this, maybe with a hint that users consider the DB collation carefully if they see odd behavior.

**Comment by jjdejong** [comment]
> The only point of weirdness is that I'm not sure how to delete a Priority Claim altogether, but that might be a UI thing.

You can only delete events, such as the priority claim, in the "All tasks" window, where you can see the related tasks that will be deleted with the events.
