### ISSUE TITLE
Logic Caseref on Matter

### ISSUE THREAD

**Issue by kojca** [jjdejong/phpip#35]
Hi jjdejong,

is Caseref an integer?

in the database the caseref is in varchar datatype, but in your code below I saw the ++ thinking it is an integer. I edited the code: **(int) $request->term** and it works when I input 01 or 02 ..... Please explain to me about this case. Thanks

`Route::get('matter/new-caseref', function (Request $request) {
        $term = (int) $request->term;
        $newref = App\Matter::where('caseref', 'like', "$term%")->max('caseref');
        $newref++;
        return [['key' => $newref, 'value' => $newref]];
    });`

**Comment by kojca** [comment]
OK, I knew your logic above. I will try to find out how to create a very first caseref with that logic.

**Comment by jjdejong** [comment]
We are speaking about the caseref autocreation logic, i.e. the new caseref suggested upon creating a matter.

The caseref is not an integer, it is any string you want, usually a string prefix followed by digits, such as "PAT001". The PHP increment ++ also operates on strings to increment them alphabetically, so if you increment "AA" you get "AB". The purpose however is to increment the numeric index of the caseref, so if you increment "PAT001", you get "PAT002". The prefix PAT is configurable in the matter_category table.

It is worth noting that the caseref autocreation logic only works properly when the database is populated with at least one matter in each category with a first caseref, such as "PAT001".

**Comment by jjdejong** [comment]
Reopened so you can react on my last comment. You prompted me to fix a glitch in the matter creation form, where the new caseref suggestion forced you to select "1" when there were no matches in the matter table. Now you can type in any value you want to create the matter - useful for populating the database with the first matters of each category.

**Comment by kojca** [comment]
> Reopened so you can react on my last comment. You prompted me to fix a glitch in the matter creation form, where the new caseref suggestion forced you to select "1" when there were no matches in the matter table. Now you can type in any value you want to create the matter - useful for populating the database with the first matters of each category.

Thank you for support. I have understood your logic.
