### ISSUE TITLE
Cannot create default_actor

### ISSUE THREAD

**Issue by kojca** [jjdejong/phpip#37]
Cannot create default_actor because:
Column not found: 1054 Unknown column 'updated_at', 'created_at' in 'field list'

**Comment by jjdejong** [comment]
That table didn't get the timestamp fields. Assigned to Papoteur who developed the UI for this table - either add the timestamps in a migration or set `$timestamps = false` in the model.

**Comment by papoteur-mga** [comment]
Hi,
Thanks for the feedback.
I added a migration file to add this columns with commit 48ea21711618ed27d99d6be2b5ac91291ae89e9e
After pulling the repository, you have to run 
php artisan migrate
