### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uqtrigger' in 'field list'

### ISSUE THREAD

**Issue by thomas2net** [jjdejong/phpip#39]
Dear Jean-Jacques,
I'm using Ubuntu Eoan and have been struggling a bit.
Facing a few errors at "php artisan migrate --seed"
To be able to move forward I commented out / added a couple of lines in install-phpip-bionic.sh

Commented out: 
echo "CREATE DATABASE phpip; GRANT ALL PRIVILEGES ON phpip.* TO phpip@localhost IDENTIFIED BY 'phpip';" | mysql       

Replaced by:                                         
echo "CREATE DATABASE phpip; CREATE USER 'phpip'@'localhost' IDENTIFIED BY 'phpip'; GRANT ALL ON phpip.* TO 'phpip'@'localhost';" | mysql                        
echo "alter user 'phpip'@'localhost' identified with mysql_native_password by 'phpip'; set global log_bin_trust_function_creators=1;" | mysql

Then I launched: php artisan migrate --seed
Which gave
(...)
Seeded:  ActorTableSeeder (0.01 seconds)
Seeding: EventNameTableSeeder

   Illuminate\Database\QueryException  : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uqtrigger' in 'field list' (SQL: insert into `event_name` (`code`, `name`, `category`, `country`, `is_task`, `status_event`, `default_responsible`, `use_matter_resp`, `unique`, `uqtrigger`, `killer`, `notes`) values (ABA, Abandoned, ?, ?, 0, 1, ?, 0, 1, 0, 1, ?))

  at /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uqtrigger' in 'field list'")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63

  2   PDOException::("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uqtrigger' in 'field list'")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61

  Please use the argument -v to see more details.

I tried using afterwards:
sudo ./install-phpip-bionic.sh 
and it gave:
(...)
********************************
Installing database
********************************
Nothing to migrate.
Seeding: CountryTableSeeder

   Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'country.PRIMARY' (SQL: insert into `country` (`em`, `ep`, `iso`, `iso3`, `name`, `name_DE`, `name_FR`, `numcode`, `oa`, `wo`) values (0, 0, AD, AND, Andorra, Andorra, Andorre, 20, 0, 0), (0, 0, AE, ARE, United Arab Emirates, Vereinigte Arabische Emirate, Émirats Arabes Unis, 784, 0, 0), (0, 0, AF, AFG, Afghanistan, Afghanistan, Afghanistan, 4, 0, 0), (0, 0, AG, ATG, Antigua and Barbuda, Antigua und Barbuda (...)
...
Zimbabwe, Simbabwe, Zimbabwe, 716, 0, 0))

  at /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'country.PRIMARY'")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123

  2   PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'country.PRIMARY'")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121

  Please use the argument -v to see more details.

********************************
Install finished. If you want to populate the database with sample data run
php artisan db:seed --class=SampleSeeder
Go to http://phpip.local and login with the credentials phpipuser:changeme

------------------
I hope this helps a bit to trace the error.
Many thanks,
Thomas

**Comment by jjdejong** [comment]
OK, try the last commit that fixes the event_name table seeder, re-run the seed, and let us know.

**Comment by thomas2net** [comment]
wget https://github.com/jjdejong/phpip/raw/master/doc/install-phpip-bionic.sh
chmod a+x install-phpip-bionic.sh
sudo ./install-phpip-bionic.sh 
--> Same error
php artisan migrate --seed
--> Same error
Maybe I need a command to clean up the mysql database first?

**Comment by jjdejong** [comment]
You can't execute the install script multiple times - you need to clean everything before a fresh execution. Apparently everything is installed already, so you only need to run the seeding, i.e. `php artisan migrate --seed`. 

Otherwise try `php artisan migrate:fresh` to uninstall all the tables and then `php artisan migrate --seed` again.

**Comment by thomas2net** [comment]
That resulted in the same output.
I then did in mysql: DROP DATABASE php
Relaunched chmod a+x install-phpip-bionic.sh
Output:
(...)
Seeding: EventNameTableSeeder

   Illuminate\Database\QueryException  : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uqtrigger' in 'field list' (SQL: insert into `event_name` (`code`, `name`, `category`, `country`, `is_task`, `status_event`, `default_responsible`, `use_matter_resp`, `unique`, `uqtrigger`, `killer`, `notes`) values (ABA, Abandoned, ?, ?, 0, 1, ?, 0, 1, 0, 1, ?))

  at /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uqtrigger' in 'field list'")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63

  2   PDOException::("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uqtrigger' in 'field list'")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61

  Please use the argument -v to see more details.

********************************
Install finished. If you want to populate the database with sample data run
php artisan db:seed --class=SampleSeeder
Go to http://phpip.local and login with the credentials phpipuser:changeme

**Comment by jjdejong** [comment]
Are you sure you pulled the last commit? That error shouldn't appear any more. 

You don't need to launch the install script again, you just need to get the command `php artisan migrate --seed` to complete without errors.

**Comment by jjdejong** [comment]
Run `git pull` to apply the last commits.

**Comment by thomas2net** [comment]
/var/www/html/phpip# git clone https://github.com/jjdejong/phpip.git /var/www/html/phpip
[did all instructions until...]

/var/www/html/phpip# php artisan migrate --seed
Nothing to migrate.
Seeding: CountryTableSeeder

   Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'country.PRIMARY' (SQL: insert into `country` (`em`, `ep`, `iso`, `iso3`, `name`, `name_DE`, `name_FR`,
(...)
Zambia, Sambia, Zambie, 894, 0, 0), (0, 0, ZW, ZWE, Zimbabwe, Simbabwe, Zimbabwe, 716, 0, 0))

  at /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'country.PRIMARY'")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123

  2   PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'country.PRIMARY'")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121

  Please use the argument -v to see more details.

**Comment by jjdejong** [comment]
OK, so you didn't have the last commit. Now you need to `php artisan migrate:fresh` and redo the full migration

**Comment by jjdejong** [comment]
Sorry, yo don't need to "redo", `migrate:fresh` does that

**Comment by thomas2net** [comment]
/var/www/html/phpip# php artisan migrate:fresh

(...)
Migrated:  2018_12_08_000109_add_trigger (0.78 seconds)
Migrating: 2018_12_08_002558_create_views_and_functions

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'task_list' already exists (SQL: CREATE
          VIEW `task_list` AS select `task`.`ID` AS `id`,
          `task`.`code` AS `code`,
          `event_name`.`name` AS `name`,
          `task`.`detail` AS `detail`,
          `task`.`due_date` AS `due_date`,
          `task`.`done` AS `done`,
          `task`.`done_date` AS `done_date`,
          `event`.`matter_ID` AS `matter_id`,
          `task`.`cost` AS `cost`,
          `task`.`fee` AS `fee`,
          `task`.`trigger_ID` AS `trigger_id`,
          `matter`.`category_code` AS `category`,
          `matter`.`caseref` AS `caseref`,
          `matter`.`country` AS `country`,
          `matter`.`origin` AS `origin`,
          `matter`.`type_code` AS `type_code`,
          `matter`.`idx` AS `idx`,
          ifnull(`task`.`assigned_to`,`matter`.`responsible`) AS `responsible`,
          `actor`.`login` AS `delegate`,
          `task`.`rule_used` AS `rule_used`,
          `matter`.`dead` AS `dead`
          from (((((`matter`
          left join `matter_actor_lnk` on(((ifnull(`matter`.`container_ID`,`matter`.`ID`) = `matter_actor_lnk`.`matter_ID`) and (`matter_actor_lnk`.`role` = 'DEL'))))
          left join `actor` on((`actor`.`ID` = `matter_actor_lnk`.`actor_ID`)))
          join `event` on((`matter`.`ID` = `event`.`matter_ID`)))
          join `task` on((`task`.`trigger_ID` = `event`.`ID`)))
          join `event_name` on((`task`.`code` = `event_name`.`code`))))

  at /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'task_list' already exists")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123

  2   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'task_list' already exists")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121

  Please use the argument -v to see more details.

**Comment by jjdejong** [comment]
Did you do `php artisan migrate:fresh`? Doesn't look like it, because the script is attempting to create views that already exist. Make sure your phpip schema is totally empty (no tables, no views, no procedures/functions). An alternative is to run `php artisan migrate:rollback` multiple times until there is nothing to rollback, and then do `php artisan migrate --seed`.

**Comment by thomas2net** [comment]
Rolling back: 2014_10_12_100000_create_password_resets_table
Rolled back:  2014_10_12_100000_create_password_resets_table (0.03 seconds)

/var/www/html/phpip# php artisan migrate:rollback
Nothing to rollback.
root@Zadyg:/var/www/html/phpip# php artisan migrate:fresh
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_100000_create_password_resets_table
(...)
Migrating: 2018_12_08_002558_create_views_and_functions

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'task_list' already exists (SQL: CREATE
          VIEW `task_list` AS select `task`.`ID` AS `id`,
          `task`.`code` AS `code`,
          `event_name`.`name` AS `name`,
          `task`.`detail` AS `detail`,
          `task`.`due_date` AS `due_date`,
          `task`.`done` AS `done`,
          `task`.`done_date` AS `done_date`,
          `event`.`matter_ID` AS `matter_id`,
          `task`.`cost` AS `cost`,
          `task`.`fee` AS `fee`,
          `task`.`trigger_ID` AS `trigger_id`,
          `matter`.`category_code` AS `category`,
          `matter`.`caseref` AS `caseref`,
          `matter`.`country` AS `country`,
          `matter`.`origin` AS `origin`,
          `matter`.`type_code` AS `type_code`,
          `matter`.`idx` AS `idx`,
          ifnull(`task`.`assigned_to`,`matter`.`responsible`) AS `responsible`,
          `actor`.`login` AS `delegate`,
          `task`.`rule_used` AS `rule_used`,
          `matter`.`dead` AS `dead`
          from (((((`matter`
          left join `matter_actor_lnk` on(((ifnull(`matter`.`container_ID`,`matter`.`ID`) = `matter_actor_lnk`.`matter_ID`) and (`matter_actor_lnk`.`role` = 'DEL'))))
          left join `actor` on((`actor`.`ID` = `matter_actor_lnk`.`actor_ID`)))
          join `event` on((`matter`.`ID` = `event`.`matter_ID`)))
          join `task` on((`task`.`trigger_ID` = `event`.`ID`)))
          join `event_name` on((`task`.`code` = `event_name`.`code`))))

  at /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'task_list' already exists")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123

  2   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'task_list' already exists")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121

  Please use the argument -v to see more details.

**Comment by thomas2net** [comment]
I cleaned and retried. Small progress:
/var/www/html/phpip# php artisan migrate:fresh
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.09 seconds)
Migrating: 2018_12_07_184310_create_actor_role_table
(...)
Migrating: 2020_02_24_192100_implement_generic_renewals
Migrated:  2020_02_24_192100_implement_generic_renewals (0.65 seconds)

/var/www/html/phpip# php artisan migrate --seed
Nothing to migrate.
Seeding: CountryTableSeeder
Seeded:  CountryTableSeeder (0.02 seconds)
Seeding: MatterCategoryTableSeeder
Seeded:  MatterCategoryTableSeeder (0.15 seconds)
Seeding: ClassifierTypeTableSeeder
Seeded:  ClassifierTypeTableSeeder (0.01 seconds)
Seeding: ActorRoleTableSeeder
Seeded:  ActorRoleTableSeeder (0.01 seconds)
Seeding: ActorTableSeeder
Seeded:  ActorTableSeeder (0.01 seconds)
Seeding: EventNameTableSeeder

   Symfony\Component\Debug\Exception\FatalThrowableError  : syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'

  at /var/www/html/phpip/database/seeds/event_name.php:4
    1| <?php
    2| $event_name = [
    3|   ['code' => 'ABA','name' => 'Abandoned','category' => NULL,'country' => NULL,'is_task' => '0','status_event' => '1','default_responsible' => NULL,'use_matter_resp' => '0','unique' => '1','killer' => '1','notes' => NULL]
  > 4|   ['code' => 'ABO','name' => 'Abandon Original','category' => 'PAT','country' => 'EP','is_task' => '1','status_event' => '0','default_responsible' => NULL,'use_matter_resp' => '0','unique' => '1','killer' => '0','notes' => 'Abandon the originating patent that was re-designated in EP']
    5|   ['code' => 'ADV','name' => 'Advisory Action','category' => 'PAT','country' => 'US','is_task' => '0','status_event' => '0','default_responsible' => NULL,'use_matter_resp' => '0','unique' => '0','killer' => '0','notes' => NULL,'updated_at' => NULL]
    6|   ['code' => 'ALL','name' => 'Allowance','category' => 'PAT','country' => NULL,'is_task' => '0','status_event' => '1','default_responsible' => NULL,'use_matter_resp' => '0','unique' => '0','killer' => '0','notes' => 'Use also for R71.3 in EP']
    7|   ['code' => 'APL','name' => 'Appeal','category' => NULL,'country' => NULL,'is_task' => '0','status_event' => '1','default_responsible' => NULL,'use_matter_resp' => '1','unique' => '0','killer' => '0','notes' => 'Appeal or other remedy filed']
    8|   ['code' => 'CAN','name' => 'Cancelled','category' => 'TM','country' => NULL,'is_task' => '0','status_event' => '1','default_responsible' => NULL,'use_matter_resp' => '0','unique' => '0','killer' => '1','notes' => NULL]
    9|   ['code' => 'CLO','name' => 'Closed','category' => 'LTG','country' => NULL,'is_task' => '0','status_event' => '1','default_responsible' => NULL,'use_matter_resp' => '0','unique' => '0','killer' => '1','notes' => NULL]

  Exception trace:

  1   EventNameTableSeeder::run()
      /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  2   call_user_func_array([])
      /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.

**Comment by jjdejong** [comment]
My fault now, I left some typos in the event_name seeder. Pull the latest commits and
`php artisan migrate:fresh --seed`

**Comment by thomas2net** [comment]
php artisan migrate:rollback
php artisan migrate:fresh --seed
(...)
Seeding: TaskRulesTableSeeder
Seeded:  TaskRulesTableSeeder (0.11 seconds)
Database seeding completed successfully.

Great! I am now able to login with phpipuser / changeme !
Many thanks J-J!
