### ISSUE TITLE
QUESTION: Installing v2 directly?

### ISSUE THREAD

**Issue by srdco** [jjdejong/phpip#4]
Is there a (straightforward) way to install v2 directly on a new Ubuntu 18.04 server -- and skip installing Zend framework, etc.?

THANKS!

**Comment by jjdejong** [comment]
Sure. You simply need to install the database first as per v1, then apply the upgrade scripts.

Note that v2 is not entirely functional yet.

**Comment by jjdejong** [comment]
Migration and seeding scripts have now been implemented for that. Check the Wiki.
