### ISSUE TITLE
Error in migration task_rules

### ISSUE THREAD

**Issue by papoteur-mga** [jjdejong/phpip#41]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; ...
'index `fk_category` to `for_category`' at line 1 (SQL: alter table `task_rules` rename index `fk_category` to `for_category`)
 database/migrations/2020_02_24_192100_implement_generic_renewals.php:44

fk_category index exists. Renaming is not allowed. I don't know why.
Here an extract from phpmyadmin, indexes from task_rules table.
![image](https://user-images.githubusercontent.com/5154580/77224219-ae64d700-6b63-11ea-84e3-d854394d11e6.png)

**Comment by papoteur-mga** [comment]
I have Mariadb 10.3.
Rename index is for MariaDB starting with 10.5.2.
Snif.

**Comment by vertbois** [comment]
Dear Sirs,

I have also Mariadb 10.3. In Navicat, we can rename the indexes. The SQL command is :

ALTER TABLE `phpip`.`task_rules`
DROP INDEX `fk_category`,
ADD INDEX `for_category`(`for_category`) USING BTREE;

After the manual change, the migration has no errors.

Regards,

[cid:image001.png@01D5FF7A.784B2020]
Samuel GRYNWALD
Tél : 06 88 32 03 71



De : Papoteur <notifications@github.com>
Envoyé : samedi 21 mars 2020 11:23
À : jjdejong/phpip <phpip@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [jjdejong/phpip] Error in migration task_rules (#41)


I have Mariadb 10.3.
Rename index is for MariaDB starting with 10.5.2.
Snif.

**Comment by jjdejong** [comment]
I didn't expect this renaming to be a problem. It's entirely optional, just for sake of naming consistency, and it can be omitted without problems. You then need to remove the renaming from the migration file and run the migration again to get it completed.

**Comment by papoteur-mga** [comment]
I succeeded to rename the index using phpmyadmin. Then the migration finished.

**Comment by alexandreIP** [comment]
A nouveau bonjour, j'arrive maintenant à 
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'renewal_first' in 'field list' (SQL: update `country` set `renewal_first` = 3 where `iso` = BE)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  **• A column was not found: You might have forgotten to run your migrations. You can run your migrations using `php artisan migrate`.** 

Pourtant j'ai l'impression d'avoir tous les fichiers de migrations...

c'est la migration: Migrating: 2020_03_28_190000_update_country

**Comment by alexandreIP** [comment]
"> I didn't expect this renaming to be a problem. It's entirely optional, just for sake of naming consistency, and it can be omitted without problems. You then need to remove the renaming from the migration file and run the migration again to get it completed."

Je viens de comprendre: j'avais interprété: supprimer le fichier...
Quelles seraient les lignes à supprimer de ce fichier ?

**Comment by jjdejong** [comment]
Même sans sans être initié au langage PHP, c'est quand même assez facile à trouver ! Puis, j'avais compris dans #43 que la migration était passée sans erreur.

**Comment by alexandreIP** [comment]
Non ca ne fonctionne pas. Ce qui fonctionnait, c'était de supprimer le fichier...

Il me semble que le script essaie de modifier le nom pour arriver au nouveau nom alors que l'ancien nom n'existe plus une fois qu'on a tapé la commande "à la main"
il faudrait faire un test sur l'existence de l'ancien nom et le cas échéant le modifier.
alter table `task_rules` rename index `fk_category` to `for_category`

j'ai fait du php, mais il y a 15 ans, avant le php objet il me semble... je vais rechercher plus finement.

**Comment by jjdejong** [comment]
Il faut supprimer les lignes
```
if (array_key_exists('fk_category', $indexes)) {
    $table->renameIndex('fk_category', 'for_category');
}
```
Dans `2020_02_24_192100_implement_generic_renewals.php`. 

Puis, si on n'est pas bricoleur, il faut se conformer aux spécifications !

**Comment by jjdejong** [comment]
Bon, j'ai modifié le script de migration pour ne pas renommer l'index, de sorte à éviter le souci à d'autres qui utiliseraient encore MariaDB 10.2...

**Comment by alexandreIP** [comment]
merci, ca passe maintenant !
