### ISSUE TITLE
mise à jour et problèmes

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#42]
Bonjour,
je n'avais pas effectué de mise à jour depuis nos derniers échanges.
Aujourd'hui, j'ai passé avec succès la commande sudo git pull.
puis la commande sudo composer install.

En revanche, la commande sudo php artisan migrate me fait le retour suivant:

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'actor_role' already exists (SQL: create table `actor_role` (`code` char(5) not null, `name` varchar(45) not null, `display_order` tinyint(1) null default '127' comment 'Order of display in interface', `shareable` tinyint(1) not null default '0' comment 'Indicates whether actors listed with this role are shareable for all matters of the same family', `show_ref` tinyint(1) not null default '0', `show_company` tinyint(1) not null default '0', `show_rate` tinyint(1) not null default '0', `show_date` tinyint(1) not null default '0', `notes` varchar(160) null, `creator` varchar(20) null, `updater` varchar(20) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

      +11 vendor frames 
  12  database/migrations/2018_12_07_184310_create_actor_role_table.php:30
      Illuminate\Support\Facades\Facade::__callStatic("create")

      +22 vendor frames 
  35  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Evidemment, plus rien ne marche: vous pouvez tenter la connection ici: https://phpip.ddns.net/login 

Comment sait on quelle version de laravel tourne sur le serveur ?

Merci beaucoup de m'avoir lu.

**Comment by alexandreIP** [comment]
l'erreur sql renvoyée lorsqu'on essaie de se connecter est: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'phpip.users' doesn't exist (SQL: select * from `users` where `login` = alexandre limit 1) 
Effectivement, il n'y a pas de table phpip.users...

**Comment by papoteur-mga** [comment]
Bonjour Alexandre,
Est-ce une installation qui contient déjà des données ?
S'il n'y a pas de données, je suggère de faire la commande qui efface les tables au préalable.
`php artisan migrate:refresh --seed`
Rajouter le sudo devant, si nécessaire, mais normalement, ça ne devrait pas l'être.

**Comment by alexandreIP** [comment]
Bonjour Jean-Jacques,
### c'est une installation qui contient des données. J'ai réussi à retrouver les données et à revenir à la version antérieure. -> à suivre
### Nénamoins, je viens d'essayer avec une installation neuve et à la commande:
php artisan migrate --seed, 
voici le résultat avec le meme type d'erreur:
Migration table created successfully.
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.37 seconds)
Migrating: 2018_12_07_184310_create_actor_role_table
Migrated:  2018_12_07_184310_create_actor_role_table (1.77 seconds)
Migrating: 2018_12_07_184310_create_actor_table
Migrated:  2018_12_07_184310_create_actor_table (4.73 seconds)
Migrating: 2018_12_07_184310_create_classifier_table
Migrated:  2018_12_07_184310_create_classifier_table (3 seconds)
Migrating: 2018_12_07_184310_create_classifier_type_table
Migrated:  2018_12_07_184310_create_classifier_type_table (1.89 seconds)
Migrating: 2018_12_07_184310_create_classifier_value_table
Migrated:  2018_12_07_184310_create_classifier_value_table (1.49 seconds)
Migrating: 2018_12_07_184310_create_country_table
Migrated:  2018_12_07_184310_create_country_table (1.56 seconds)
Migrating: 2018_12_07_184310_create_default_actor_table
Migrated:  2018_12_07_184310_create_default_actor_table (1.81 seconds)
Migrating: 2018_12_07_184310_create_event_name_table
Migrated:  2018_12_07_184310_create_event_name_table (1.72 seconds)
Migrating: 2018_12_07_184310_create_event_table
Migrated:  2018_12_07_184310_create_event_table (3.14 seconds)
Migrating: 2018_12_07_184310_create_matter_actor_lnk_table
Migrated:  2018_12_07_184310_create_matter_actor_lnk_table (2.84 seconds)
Migrating: 2018_12_07_184310_create_matter_category_table
Migrated:  2018_12_07_184310_create_matter_category_table (3.48 seconds)
Migrating: 2018_12_07_184310_create_matter_table
Migrated:  2018_12_07_184310_create_matter_table (4.21 seconds)
Migrating: 2018_12_07_184310_create_matter_type_table
Migrated:  2018_12_07_184310_create_matter_type_table (0.64 seconds)
Migrating: 2018_12_07_184310_create_task_rules_table
Migrated:  2018_12_07_184310_create_task_rules_table (6.43 seconds)
Migrating: 2018_12_07_184310_create_task_table
Migrated:  2018_12_07_184310_create_task_table (3.3 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_actor_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_actor_table (19.97 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_classifier_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_classifier_table (7.13 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_classifier_type_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_classifier_type_table (2.35 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_classifier_value_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_classifier_value_table (0.71 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_default_actor_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_default_actor_table (7.04 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_event_name_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_event_name_table (1.48 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_event_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_event_table (3.25 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_matter_actor_lnk_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_matter_actor_lnk_table (5.95 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_matter_category_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_matter_category_table (1.18 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_matter_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_matter_table (8.47 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_task_rules_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_task_rules_table (9.85 seconds)
Migrating: 2018_12_07_184312_add_foreign_keys_to_task_table
Migrated:  2018_12_07_184312_add_foreign_keys_to_task_table (3.42 seconds)
Migrating: 2018_12_08_000109_add_trigger
Migrated:  2018_12_08_000109_add_trigger (2.01 seconds)
Migrating: 2018_12_08_002558_create_views_and_functions
Migrated:  2018_12_08_002558_create_views_and_functions (0.41 seconds)
Migrating: 2019_03_07_171752_create_procedure_recalculate_tasks
Migrated:  2019_03_07_171752_create_procedure_recalculate_tasks (0.03 seconds)
Migrating: 2019_03_07_171910_create_procedure_recreate_tasks
Migrated:  2019_03_07_171910_create_procedure_recreate_tasks (0.04 seconds)
Migrating: 2019_08_13_145446_update_tables
Migrated:  2019_08_13_145446_update_tables (1.17 seconds)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (0.16 seconds)
Migrating: 2019_11_13_135330_update_tables2
Migrated:  2019_11_13_135330_update_tables2 (0.96 seconds)
Migrating: 2019_11_17_025422_update_tables3
Migrated:  2019_11_17_025422_update_tables3 (1.67 seconds)
Migrating: 2019_11_18_002207_update_tables4
Migrated:  2019_11_18_002207_update_tables4 (0.08 seconds)
Migrating: 2019_11_25_123348_update_tables5
Migrated:  2019_11_25_123348_update_tables5 (0.49 seconds)
Migrating: 2019_11_26_192706_create_user_view
Migrated:  2019_11_26_192706_create_user_view (0.02 seconds)
Migrating: 2020_01_06_181200_update_tables6
Migrated:  2020_01_06_181200_update_tables6 (0.85 seconds)
Migrating: 2020_01_21_173000_update_tables7
Migrated:  2020_01_21_173000_update_tables7 (0.41 seconds)
Migrating: 2020_01_28_122217_update_db_roles
Migrated:  2020_01_28_122217_update_db_roles (0.02 seconds)
Migrating: 2020_02_02_105653_add_timestamps_default_actors
Migrated:  2020_02_02_105653_add_timestamps_default_actors (0.03 seconds)
Migrating: 2020_02_12_144400_update_procedure_update_expired
Migrated:  2020_02_12_144400_update_procedure_update_expired (0.03 seconds)
Migrating: 2020_02_24_110300_update_tables8c
Migrated:  2020_02_24_110300_update_tables8c (0.23 seconds)
Migrating: 2020_02_24_190000_update_rules2
Migrated:  2020_02_24_190000_update_rules2 (0.05 seconds)
Migrating: 2020_02_24_192100_implement_generic_renewals

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'index `fk_category` to `for_category`' at line 1 (SQL: alter table `task_rules` rename index `fk_category` to `for_category`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

      +11 vendor frames 
  12  database/migrations/2020_02_24_192100_implement_generic_renewals.php:43
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +22 vendor frames 
  35  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by alexandreIP** [comment]
Je viens de faire php artisan migrate:refresh --seed sur cette nouvelle base et cela recommence à la toute fin:
 Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'index `fk_category` to `for_category`' at line 1 (SQL: alter table `task_rules` rename index `fk_category` to `for_category`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

      +11 vendor frames 
  12  database/migrations/2020_02_24_192100_implement_generic_renewals.php:43
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +34 vendor frames 
  47  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by alexandreIP** [comment]
J'ai aussi cet erreur sur la nouvelle base: 
UnexpectedValueException
The stream or file "/var/www/html/phpipv4/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied 

Je fais tourner cela sur une Raspberry (cela marchait très bien avec la précédente version de phpipV2.

**Comment by papoteur-mga** [comment]
Moi, c'est Yves.
Ceci vient de la version de mariaDB. J'ai eu le même problème avec une 10.3. Il faut une 10.5.
Jean-Jacques a indiqué que ce n'était pas vital.
Voir #41 
J'ai fait la modification manuellement depuis phpMyAdmin, puis la migration passe.

**Comment by jjdejong** [comment]
Il n'y a pas besoin de "sudo" pour `php artisan migrate`.  La commande utilise les identifiants de la connexion dans .env.

Puis si vous n'utilisez pas la plateforeme préconisée, attendez vous à des artéfacts non documentés par les développeurs, hein.

**Comment by jjdejong** [comment]
> Il n'y a pas besoin de "sudo" pour `php artisan migrate`. La commande utilise les identifiants de la connexion dans .env.

En fait si, dans le cas où le fichier storage/logs/laravel.log n'est pas accessible en écriture par l'utilisateur !
