### ISSUE TITLE
colum "renwal_first"

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#43]
Bonjour Jean-Jacques, Yves,
je n'arrive pas à passer le script d'hier sur la base neuve, car il me manque une colonne dans la table country.
De ce fait, j'ai recherché quel script sql du passé créait cette colonne mais je n'ai pas trouvé.
Auriez-vous une solution pour celà ?

Question subsidiaire: comment faites vous pour créer une base de test avec les données de la bases de productions pour pouvoir tester les mises à jour avant de les appliquer sur la base de production ?

Bien à vous
Alexandre

Migrating: 2020_03_28_190000_update_country

   Illuminate\Database\QueryException 

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'renewal_first' in 'field list' (SQL: update `country` set `renewal_first` = 3 where `iso` = BE)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  • A column was not found: You might have forgotten to run your migrations. You can run your migrations using `php artisan migrate`. 
    https://laravel.com/docs/master/migrations#running-migrations

      +9 vendor frames 
  10  database/migrations/2020_03_28_190000_update_country.php:16
      Illuminate\Database\Query\Builder::update([])

      +22 vendor frames 
  33  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by jjdejong** [comment]
Les tables sont créées avec des scripts de migration. Le script qui crée la colonne qui te manque est `2020_02_24_192100_implement_generic_renewals.php`. Donc apparemment ce script n'a pas été exécuté. Regarde dans la table "migrations" pour voir les scripts qui ont été exécutés avec succès.

**Comment by alexandreIP** [comment]
merci !
ce fichier était absent (car je l'avais effacé). J'ai téléchargé le fichier, l'ai placé dans le répertoire, et ai relancé, cela fonctionne maintenant:

php artisan migrate
Migrating: 2020_02_24_192100_implement_generic_renewals
Migrated:  2020_02_24_192100_implement_generic_renewals (5.76 seconds)
Migrating: 2020_03_28_190000_update_country
Migrated:  2020_03_28_190000_update_country (0.69 seconds)

**Comment by jjdejong** [comment]
Faudra nous payer une bière !
