### ISSUE TITLE
Je ne peux plus rien éditer...

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#44]
vraiment désolé...
Je ne peux plus rien modifier sur ma base de prod avec mon login/mdp habituels.
Que dois je vérifier dans la base de données ? Faut il que je m'assigne un rôle par défaut: lequel?
(jusque là je n'en avais pas et ca fonctionnait)

(Au passage, j'ai installé une base de données neuve avec le jeu de données que vous proposez et l'adresse email d'un yves est fournie.)

**Comment by jjdejong** [comment]
En effet, c'est quelque chose que je dois encore documenter depuis la création d'un système de permissions - il faut attribuer `default_role='DBA'` à l'utilisateur en question, soit avec phpMyAdmin ou autre.

**Comment by alexandreIP** [comment]
J'avais essayé cela en parallèle et je confirme que cela fonctionne ...
à noter aussi que dans la base obtenue avec php artisan db:seed --class=SampleSeeder, l'user phpipuser n'a pas non plus le rôle de DBA dans default rôle

**Comment by jjdejong** [comment]
Oui, car ces rôles "DBxx" ont été ajoutés après. Je viens d'ajouter l'affectation du rôle DBA à phpipuser dans `2020_01_28_122217_update_db_roles.php`.
