### ISSUE TITLE
Payor reference

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#47]
Lors de l'ajout d'un acteur avec le rôle "payor", il est possible d'ajouter une référence de cet acteur pour le dossier.
Néanmoins, la référence ne s'affiche pas dans l'UI.

**Comment by jjdejong** [comment]
Ceci n'est pas un bug.

Les informations d'acteur à afficher dans un dossier sont configurables pour chaque rôle dans la table des rôles (menu Tables->Actor roles). Sinon toutes les informations sont accessibles et éditables en cliquant le crayon dans l'en-tête de rôle.
