### ISSUE TITLE
Renewal management UI - XML payment order

### ISSUE THREAD

**Issue by jjdejong** [jjdejong/phpip#54]
This XML file is created with all the checked renewals, irrespective of the countries, generating one file combining the multiple countries. One separate file should be created for each country.

**Comment by papoteur-mga** [comment]
Indeed, but in my idea you know to which office you want to send an order, thus you select renewals for this juridiction, no ?
What I can add is a error message that renewals for more than one juridiction are selected.

**Comment by jjdejong** [comment]
In an office with more or less competent administrative staff, it cannot be assumed that the user will always have such details in mind! The software should always anticipate possible human errors.
