### ISSUE TITLE
pb when running php artisan migrate

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#69]
Happy new year !
I just made un update from last tim with git pull then with composer install. All went well except unless php artisan migrate (see end of message)
The phpip system seems to work.

pi@raspberrypi:/var/www/html/phpipf $ git pull
remote: Enumerating objects: 794, done.
remote: Counting objects: 100% (794/794), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 1870 (delta 777), reused 791 (delta 775), pack-reused 1076
Réception d'objets: 100% (1870/1870), 655.52 KiB | 1.48 MiB/s, fait.
Résolution des deltas: 100% (1349/1349), complété avec 115 objets locaux.
Depuis https://github.com/jjdejong/phpip
   4c682c1..95d6a98  master     -> origin/master
 * [nouvelle branche] dependabot/npm_and_yarn/websocket-extensions-0.1.4 -> origin/dependabot/npm_and_yarn/websocket-extensions-0.1.4
Mise à jour 4c682c1..95d6a98
Fast-forward
 .env.example                                       |   26 +-
 .gitignore                                         |    3 +-
 app/Event.php                                      |    3 +
 app/EventClassLnk.php                              |   15 +
 app/EventName.php                                  |    3 +
 app/Fee.php                                        |   26 +
 app/Http/Controllers/ActorController.php           |   48 +-
 app/Http/Controllers/ActorPivotController.php      |  109 +-
 app/Http/Controllers/CategoryController.php        |    5 +-
 app/Http/Controllers/ClassifierController.php      |   44 +-
 app/Http/Controllers/ClassifierTypeController.php  |    5 +-
 app/Http/Controllers/DefaultActorController.php    |    8 +-
 app/Http/Controllers/DocumentController.php        |  279 +
 app/Http/Controllers/EventClassController.php      |   37 +
 app/Http/Controllers/EventController.php           |   35 +-
 app/Http/Controllers/EventNameController.php       |    9 +-
 app/Http/Controllers/FeeController.php             |  136 +
 app/Http/Controllers/HomeController.php            |   41 +-
 app/Http/Controllers/MatterController.php          |  425 +-
 app/Http/Controllers/MatterTypeController.php      |    5 +-
 app/Http/Controllers/RenewalController.php         |  980 ++
 app/Http/Controllers/RoleController.php            |    5 +-
 app/Http/Controllers/RuleController.php            |    6 +-
 app/Http/Controllers/TaskController.php            |   17 +-
 app/Http/Controllers/TemplateMemberController.php  |  135 +
 app/Http/Controllers/UserController.php            |   27 +-
 app/Language.php                                   |   10 +
 app/Mail/sendCall.php                              |   75 +
 app/Matter.php                                     |  390 +-
 app/MatterActors.php                               |   12 +-
 app/Policies/MatterPolicy.php                      |   36 +-
 app/Providers/AppServiceProvider.php               |    3 +-
 app/RenewalsLog.php                                |   33 +
 app/Rule.php                                       |    4 +
 app/Task.php                                       |  159 +-
 app/TemplateClass.php                              |   25 +
 app/TemplateMember.php                             |   15 +
 composer.json                                      |   27 +-
 composer.lock                                      | 3394 ++++---
 config/logging.php                                 |    2 +-
 config/renewal.php.example                         |  105 +
 database/factories/UserFactory.php                 |   50 +-
 .../2018_12_07_184310_create_task_rules_table.php  |    1 +
 .../migrations/2018_12_08_000109_add_trigger.php   |    2 +-
 ...7_171752_create_procedure_recalculate_tasks.php |    3 +-
 .../2019_12_06_000000_create_fees_table.php        |   51 +
 .../migrations/2019_12_06_002_alter_task_table.php |   87 +
 .../2019_12_06_003_create_renewal_list_view.php    |   76 +
 .../2020_01_30_001_create_renewals_logs_table.php  |   45 +
 .../2020_02_22_161215_create_template_classes.php  |   39 +
 .../2020_02_22_164446_create_template_members.php  |   41 +
 .../2020_02_22_173742_create_event_class_lnk.php   |   33 +
 ..._181558_add_foreignkeys_to_template_members.php |   32 +
 ..._183512_add_foreignkeys_to_template_classes.php |   32 +
 ...020_02_24_192100_implement_generic_renewals.php |   26 +-
 .../2020_03_23_110300_update_tables9c.php          |   64 +
 ...2_183512_add_foreignkeys_to_event_class_lnk.php |   34 +
 .../2020_04_15_110300_update_tables10.php          |   93 +
 .../2020_06_16_122700_update_actor_lang.php        |   75 +
 .../2020_06_23_200200_remove_parent_filed_deps.php |  535 ++
 ..._07_29_190800_fix_insert_recurring_renewals.php |   73 +
 .../2020_07_30_091000_update_special_countries.php |   87 +
 .../2020_09_18_135000_update_tables11.php          |   44 +
 ...20_10_01_130832_update_category_provisional.php |   29 +
 .../2020_12_04_133640_update_matter_alt_ref.php    |   33 +
 database/migrations/sql/dump-structure.sh          |    5 +
 database/migrations/sql/phpip-data.sql             |  978 ++
 database/migrations/sql/phpip-structure.sql        | 2116 +++++
 database/seeders/ActorRoleTableSeeder.php          |  356 +
 database/{seeds => seeders}/ActorSampleSeeder.php  |    5 +-
 database/seeders/ActorTableSeeder.php              |   94 +
 .../{seeds => seeders}/ClassifierSampleSeeder.php  |    4 +-
 database/seeders/ClassifierTypeTableSeeder.php     |  306 +
 database/seeders/CountryTableSeeder.php            | 4273 +++++++++
 database/{seeds => seeders}/DatabaseSeeder.php     |    5 +
 database/seeders/EventNameTableSeeder.php          | 1138 +++
 database/{seeds => seeders}/EventSampleSeeder.php  |    5 +-
 database/seeders/FeesTableSeeder.php               | 3378 +++++++
 database/seeders/MatterCategoryTableSeeder.php     |  196 +
 database/{seeds => seeders}/MatterSampleSeeder.php |    8 +-
 database/seeders/MatterTypeTableSeeder.php         |   65 +
 database/{seeds => seeders}/SampleSeeder.php       |    2 +
 database/seeders/TaskRulesTableSeeder.php          | 8179 ++++++++++++++++
 database/{seeds => seeders}/TaskSampleSeeder.php   |    5 +-
 database/seeders/TemplateClassesTableSeeder.php    |   31 +
 database/seeders/TemplateMembersTableSeeder.php    |   68 +
 database/seeders/actor-sample.php                  |  212 +
 database/seeders/classifier-sample.php             |    5 +
 database/seeders/event-sample.php                  |   28 +
 database/seeders/matter-sample.php                 |   15 +
 database/seeders/matter_actor_lnk-sample.php       |   11 +
 database/seeders/task-sample.php                   |   31 +
 database/seeds/ActorRoleTableSeeder.php            |   18 -
 database/seeds/ActorTableSeeder.php                |   17 -
 database/seeds/ClassifierTypeTableSeeder.php       |   18 -
 database/seeds/CountryTableSeeder.php              |   17 -
 database/seeds/EventNameTableSeeder.php            |   21 -
 database/seeds/MatterCategoryTableSeeder.php       |   22 -
 database/seeds/MatterTypeTableSeeder.php           |   17 -
 database/seeds/TaskRulesTableSeeder.php            |   17 -
 database/seeds/actor-sample.php                    |   10 -
 database/seeds/actor.php                           |   61 -
 database/seeds/actor_role.php                      |   21 -
 database/seeds/classifier-sample.php               |    5 -
 database/seeds/classifier_type.php                 |   24 -
 database/seeds/country.php                         |  260 -
 database/seeds/event-sample.php                    |   34 -
 database/seeds/event_name.php                      |   65 -
 database/seeds/matter-sample.php                   |   20 -
 database/seeds/matter_actor_lnk-sample.php         |   11 -
 database/seeds/matter_category.php                 |   30 -
 database/seeds/matter_type.php                     |   18 -
 database/seeds/task-sample.php                     |   36 -
 database/seeds/task.php                            |   36 -
 database/seeds/task_rules.php                      |  240 -
 doc/Renewal workflow.ods                           |  Bin 0 -> 14646 bytes
 doc/install-phpip-bionic.sh                        |    2 +-
 package-lock.json                                  | 9882 --------------------
 package.json                                       |    3 +-
 public/css/app.css                                 |   12 +-
 public/js/app.js                                   |    2 +-
 public/js/app.js.LICENSE.txt                       |   14 +-
 resources/js/bootstrap.js                          |    6 +-
 resources/scripts/.gitignore                       |    1 +
 .../scripts/{sga2.ini.example => aqs.ini.example}  |    2 +
 resources/scripts/aqs.php                          |  300 +
 resources/scripts/email-tasks.ini.example          |    9 +
 resources/scripts/email-tasks.php                  |   69 +
 resources/scripts/sga2.php                         |  262 -
 resources/views/actor/show.blade.php               |    8 +
 resources/views/documents/create.blade.php         |   24 +
 resources/views/documents/index.blade.php          |   57 +
 resources/views/documents/select.blade.php         |   74 +
 resources/views/documents/select2.blade.php        |   79 +
 resources/views/documents/show.blade.php           |   27 +
 resources/views/email/renewalCall.blade.php        |   65 +
 resources/views/eventname/show.blade.php           |   36 +-
 resources/views/fee/create.blade.php               |   37 +
 resources/views/fee/index.blade.php                |   89 +
 resources/views/home-js.blade.php                  |  121 +-
 resources/views/home.blade.php                     |    5 +-
 resources/views/layouts/app.blade.php              |  169 +-
 resources/views/matter/create.blade.php            |    2 +-
 resources/views/matter/edit.blade.php              |   10 +-
 resources/views/matter/events.blade.php            |   16 +-
 resources/views/matter/index.blade.php             |  166 +-
 resources/views/matter/show-js.blade.php           |   54 +-
 resources/views/matter/show.blade.php              |   50 +-
 resources/views/matter/tasks.blade.php             |   71 +-
 resources/views/renewals/index.blade.php           |  480 +
 resources/views/renewals/logs.blade.php            |   61 +
 resources/views/rule/create.blade.php              |   21 +-
 resources/views/rule/show.blade.php                |   35 +-
 resources/views/task/index.blade.php               |   59 +-
 resources/views/template-members/create.blade.php  |   53 +
 resources/views/template-members/index.blade.php   |   63 +
 resources/views/template-members/show.blade.php    |   41 +
 .../views/vendor/pagination/bootstrap-4.blade.php  |   46 +
 .../vendor/pagination/simple-bootstrap-4.blade.php |   27 +
 routes/web.php                                     |  116 +-
 tests/TestCase.php                                 |    1 +
 yarn.lock                                          | 3168 +++----
 162 files changed, 31642 insertions(+), 15097 deletions(-)
 create mode 100644 app/EventClassLnk.php
 create mode 100644 app/Fee.php
 create mode 100644 app/Http/Controllers/DocumentController.php
 create mode 100644 app/Http/Controllers/EventClassController.php
 create mode 100644 app/Http/Controllers/FeeController.php
 create mode 100644 app/Http/Controllers/RenewalController.php
 create mode 100644 app/Http/Controllers/TemplateMemberController.php
 create mode 100644 app/Language.php
 create mode 100644 app/Mail/sendCall.php
 create mode 100644 app/RenewalsLog.php
 create mode 100644 app/TemplateClass.php
 create mode 100644 app/TemplateMember.php
 create mode 100644 config/renewal.php.example
 create mode 100644 database/migrations/2019_12_06_000000_create_fees_table.php
 create mode 100644 database/migrations/2019_12_06_002_alter_task_table.php
 create mode 100644 database/migrations/2019_12_06_003_create_renewal_list_view.php
 create mode 100644 database/migrations/2020_01_30_001_create_renewals_logs_table.php
 create mode 100644 database/migrations/2020_02_22_161215_create_template_classes.php
 create mode 100644 database/migrations/2020_02_22_164446_create_template_members.php
 create mode 100644 database/migrations/2020_02_22_173742_create_event_class_lnk.php
 create mode 100644 database/migrations/2020_02_22_181558_add_foreignkeys_to_template_members.php
 create mode 100644 database/migrations/2020_02_22_183512_add_foreignkeys_to_template_classes.php
 create mode 100644 database/migrations/2020_03_23_110300_update_tables9c.php
 create mode 100644 database/migrations/2020_04_12_183512_add_foreignkeys_to_event_class_lnk.php
 create mode 100644 database/migrations/2020_04_15_110300_update_tables10.php
 create mode 100644 database/migrations/2020_06_16_122700_update_actor_lang.php
 create mode 100644 database/migrations/2020_06_23_200200_remove_parent_filed_deps.php
 create mode 100644 database/migrations/2020_07_29_190800_fix_insert_recurring_renewals.php
 create mode 100644 database/migrations/2020_07_30_091000_update_special_countries.php
 create mode 100644 database/migrations/2020_09_18_135000_update_tables11.php
 create mode 100644 database/migrations/2020_10_01_130832_update_category_provisional.php
 create mode 100644 database/migrations/2020_12_04_133640_update_matter_alt_ref.php
 create mode 100644 database/migrations/sql/dump-structure.sh
 create mode 100644 database/migrations/sql/phpip-data.sql
 create mode 100644 database/migrations/sql/phpip-structure.sql
 create mode 100644 database/seeders/ActorRoleTableSeeder.php
 rename database/{seeds => seeders}/ActorSampleSeeder.php (81%)
 create mode 100644 database/seeders/ActorTableSeeder.php
 rename database/{seeds => seeders}/ClassifierSampleSeeder.php (72%)
 create mode 100644 database/seeders/ClassifierTypeTableSeeder.php
 create mode 100644 database/seeders/CountryTableSeeder.php
 rename database/{seeds => seeders}/DatabaseSeeder.php (76%)
 create mode 100644 database/seeders/EventNameTableSeeder.php
 rename database/{seeds => seeders}/EventSampleSeeder.php (73%)
 create mode 100644 database/seeders/FeesTableSeeder.php
 create mode 100644 database/seeders/MatterCategoryTableSeeder.php
 rename database/{seeds => seeders}/MatterSampleSeeder.php (66%)
 create mode 100644 database/seeders/MatterTypeTableSeeder.php
 rename database/{seeds => seeders}/SampleSeeder.php (93%)
 create mode 100644 database/seeders/TaskRulesTableSeeder.php
 rename database/{seeds => seeders}/TaskSampleSeeder.php (63%)
 create mode 100644 database/seeders/TemplateClassesTableSeeder.php
 create mode 100644 database/seeders/TemplateMembersTableSeeder.php
 create mode 100644 database/seeders/actor-sample.php
 create mode 100644 database/seeders/classifier-sample.php
 create mode 100644 database/seeders/event-sample.php
 create mode 100644 database/seeders/matter-sample.php
 create mode 100644 database/seeders/matter_actor_lnk-sample.php
 create mode 100644 database/seeders/task-sample.php
 delete mode 100644 database/seeds/ActorRoleTableSeeder.php
 delete mode 100644 database/seeds/ActorTableSeeder.php
 delete mode 100644 database/seeds/ClassifierTypeTableSeeder.php
 delete mode 100644 database/seeds/CountryTableSeeder.php
 delete mode 100644 database/seeds/EventNameTableSeeder.php
 delete mode 100644 database/seeds/MatterCategoryTableSeeder.php
 delete mode 100644 database/seeds/MatterTypeTableSeeder.php
 delete mode 100644 database/seeds/TaskRulesTableSeeder.php
 delete mode 100644 database/seeds/actor-sample.php
 delete mode 100644 database/seeds/actor.php
 delete mode 100644 database/seeds/actor_role.php
 delete mode 100644 database/seeds/classifier-sample.php
 delete mode 100644 database/seeds/classifier_type.php
 delete mode 100644 database/seeds/country.php
 delete mode 100644 database/seeds/event-sample.php
 delete mode 100644 database/seeds/event_name.php
 delete mode 100644 database/seeds/matter-sample.php
 delete mode 100644 database/seeds/matter_actor_lnk-sample.php
 delete mode 100644 database/seeds/matter_category.php
 delete mode 100644 database/seeds/matter_type.php
 delete mode 100644 database/seeds/task-sample.php
 delete mode 100644 database/seeds/task.php
 delete mode 100644 database/seeds/task_rules.php
 create mode 100644 doc/Renewal workflow.ods
 delete mode 100644 package-lock.json
 create mode 100644 resources/scripts/.gitignore
 rename resources/scripts/{sga2.ini.example => aqs.ini.example} (88%)
 create mode 100755 resources/scripts/aqs.php
 create mode 100644 resources/scripts/email-tasks.ini.example
 create mode 100755 resources/scripts/email-tasks.php
 delete mode 100755 resources/scripts/sga2.php
 create mode 100644 resources/views/documents/create.blade.php
 create mode 100644 resources/views/documents/index.blade.php
 create mode 100644 resources/views/documents/select.blade.php
 create mode 100644 resources/views/documents/select2.blade.php
 create mode 100644 resources/views/documents/show.blade.php
 create mode 100644 resources/views/email/renewalCall.blade.php
 create mode 100644 resources/views/fee/create.blade.php
 create mode 100644 resources/views/fee/index.blade.php
 create mode 100644 resources/views/renewals/index.blade.php
 create mode 100644 resources/views/renewals/logs.blade.php
 create mode 100644 resources/views/template-members/create.blade.php
 create mode 100644 resources/views/template-members/index.blade.php
 create mode 100644 resources/views/template-members/show.blade.php
 create mode 100644 resources/views/vendor/pagination/bootstrap-4.blade.php
 create mode 100644 resources/views/vendor/pagination/simple-bootstrap-4.blade.php

pi@raspberrypi:/var/www/html/phpipf $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 18 installs, 85 updates, 6 removals
  - Removing scrivo/highlight.php (v9.18.1.1)
  - Removing phpunit/php-token-stream (3.1.1)
  - Removing jakub-onderka/php-console-highlighter (v0.4)
  - Removing jakub-onderka/php-console-color (v0.2)
  - Removing fzaninotto/faker (v1.9.1)
  - Removing caouecs/laravel-lang (4.0.11)
  - Updating doctrine/event-manager (1.1.0 => 1.1.1): Downloading (100%)          - Updating doctrine/cache (1.10.0 => 1.10.2): Downloading (100%)         
  - Updating doctrine/dbal (v2.10.1 => 2.12.1): Downloading (100%)         
  - Updating doctrine/inflector (1.3.1 => 2.0.3): Downloading (100%)         
  - Updating doctrine/lexer (1.2.0 => 1.2.1): Downloading (100%)         
  - Updating symfony/polyfill-ctype (v1.15.0 => v1.20.0): Downloading (100%)      - Updating webmozart/assert (1.7.0 => 1.9.1): Downloading (100%)         
  - Updating dragonmantank/cron-expression (v2.3.0 => v3.1.0):Downloading (100%)  - Updating voku/portable-ascii (1.4.10 => 1.5.6): Downloading (100%)         
  - Installing symfony/polyfill-php80 (v1.20.0): Downloading (100%)         
  - Updating symfony/polyfill-mbstring (v1.15.0 => v1.20.0): Downloading (100%)   - Updating phpoption/phpoption (1.7.3 => 1.7.5): Downloading (100%)         
  - Installing graham-campbell/result-type (v1.0.1):Downloading (100%)         )
  - Updating vlucas/phpdotenv (v4.1.3 => v5.2.0): Downloading (100%)         
  - Updating symfony/css-selector (v5.0.7 => v5.2.1): Downloading (100%)          - Updating tijsverkoyen/css-to-inline-styles (2.2.2 => 2.2.3): Downloading (100%)         
  - Updating symfony/var-dumper (v5.0.7 => v5.2.1): Downloading (100%)         
  - Installing symfony/deprecation-contracts (v2.2.0): Downloading (100%)         - Updating symfony/routing (v5.0.7 => v5.2.1): Downloading (100%)         
  - Updating symfony/process (v5.0.7 => v5.2.1): Downloading (100%)         
  - Updating symfony/polyfill-php72 (v1.15.0 => v1.20.0): Downloading (100%)      - Installing symfony/polyfill-intl-normalizer (v1.20.0): Downloading (100%)     - Updating symfony/polyfill-intl-idn (v1.15.0 => v1.20.0): Downloading (100%)   - Updating symfony/mime (v5.0.7 => v5.2.1): Downloading (100%)         
  - Updating symfony/polyfill-php73 (v1.15.0 => v1.20.0): Downloading (100%)      - Updating symfony/http-foundation (v5.0.7 => v5.2.1): Downloading (100%)       - Installing symfony/http-client-contracts (v2.3.1): Downloading (100%)         - Updating symfony/event-dispatcher-contracts (v2.0.1 => v2.2.0): Downloading (100%)         
  - Updating symfony/event-dispatcher (v5.0.7 => v5.2.1): Downloading (100%)      - Updating symfony/error-handler (v5.0.7 => v5.2.1): Downloading (100%)         - Updating symfony/http-kernel (v5.0.7 => v5.2.1):Downloading (100%)         )
  - Updating symfony/finder (v5.0.7 => v5.2.1): Downloading (100%)         
  - Installing symfony/polyfill-intl-grapheme (v1.20.0): Downloading (100%)       - Installing symfony/string (v5.2.1): Downloading (100%)         
  - Updating symfony/service-contracts (v2.0.1 => v2.2.0): Downloading (100%)     - Updating symfony/console (v5.0.7 => v5.2.1): Downloading (100%)         
  - Updating symfony/polyfill-iconv (v1.15.0 => v1.20.0): Downloading (100%)      - Updating egulias/email-validator (2.1.17 => 2.1.25): Downloading (100%)       - Updating swiftmailer/swiftmailer (v6.2.3 => v6.2.4): Downloading (100%)       - Updating ramsey/collection (1.0.1 => 1.1.1): Downloading (100%)         
  - Updating brick/math (0.8.14 => 0.9.1): Downloading (100%)         
  - Updating ramsey/uuid (4.0.1 => 4.1.1): Downloading (100%)         
  - Updating opis/closure (3.5.1 => 3.6.1): Downloading (100%)         
  - Updating symfony/translation-contracts (v2.0.1 => v2.3.0):Downloading (100%)  - Updating symfony/translation (v5.0.7 => v5.2.1):Downloading (100%)         )
  - Updating nesbot/carbon (2.32.1 => 2.43.0): Downloading (100%)         
  - Updating monolog/monolog (2.0.2 => 2.2.0): Downloading (100%)         
  - Installing league/mime-type-detection (1.5.1): Downloading (100%)         
  - Updating league/flysystem (1.0.66 => 1.1.3): Downloading (100%)         
  - Updating league/commonmark (1.3.2 => 1.5.7): Downloading (100%)         
  - Updating laravel/framework (v7.3.0 => v8.21.0): Downloading (100%)         
  - Updating fideloper/proxy (4.3.0 => 4.4.1): Downloading (100%)         
  - Updating fruitcake/laravel-cors (v1.0.5 => v1.0.6): Loading from cache
  - Installing psr/http-client (1.0.1): Downloading (100%)         
  - Updating guzzlehttp/psr7 (1.6.1 => 1.7.0): Downloading (100%)         
  - Updating guzzlehttp/promises (v1.3.1 => 1.4.0): Downloading (100%)         
  - Updating guzzlehttp/guzzle (6.5.2 => 7.2.0): Downloading (100%)         
  - Updating nikic/php-parser (v4.3.0 => v4.10.4): Downloading (100%)         
  - Updating psy/psysh (v0.10.2 => v0.10.5): Downloading (100%)         
  - Updating laravel/tinker (v2.3.0 => v2.5.0): Downloading (100%)         
  - Updating laravel/ui (v2.0.1 => v3.2.0): Downloading (100%)         
  - Updating filp/whoops (2.7.1 => 2.9.1): Downloading (100%)         
  - Updating facade/ignition-contracts (1.0.0 => 1.0.2): Downloading (100%)       - Updating facade/flare-client-php (1.3.2 => 1.3.7): Downloading (100%)         - Updating facade/ignition (2.0.2 => 2.5.8): Downloading (100%)         
  - Updating hamcrest/hamcrest-php (v2.0.0 => v2.0.1): Downloading (100%)         - Updating mockery/mockery (1.3.1 => 1.4.2): Downloading (100%)         
  - Updating nunomaduro/collision (v4.1.3 => v5.1.0): Downloading (100%)          - Updating phpdocumentor/reflection-common (2.0.0 => 2.2.0):Downloading (100%)  - Updating phpdocumentor/type-resolver (1.1.0 => 1.4.0): Downloading (100%)     - Updating phpdocumentor/reflection-docblock (5.1.0 => 5.2.2): Downloading (100%)         
  - Updating sebastian/version (2.0.1 => 3.0.2): Downloading (100%)         
  - Updating sebastian/type (1.1.3 => 2.3.1): Downloading (100%)         
  - Updating sebastian/resource-operations (2.0.1 => 3.0.3): Downloading (100%)   - Updating sebastian/recursion-context (3.0.0 => 4.0.4): Downloading (100%)     - Updating sebastian/object-reflector (1.1.1 => 2.0.4): Downloading (100%)      - Updating sebastian/object-enumerator (3.0.3 => 4.0.4): Downloading (100%)     - Updating sebastian/global-state (3.0.0 => 5.0.2): Downloading (100%)          - Updating sebastian/exporter (3.1.2 => 4.0.3): Downloading (100%)         
  - Updating sebastian/environment (4.2.3 => 5.1.3):Downloading (100%)         )
  - Updating sebastian/diff (3.0.2 => 4.0.4): Downloading (100%)         
  - Updating sebastian/comparator (3.0.2 => 4.0.6): Downloading (100%)         
  - Installing sebastian/code-unit (1.0.8): Downloading (100%)         
  - Installing sebastian/cli-parser (1.0.1): Downloading (100%)         
  - Updating phpunit/php-timer (2.1.2 => 5.0.3): Downloading (100%)         
  - Updating phpunit/php-text-template (1.2.1 => 2.0.4): Downloading (100%)       - Installing phpunit/php-invoker (3.1.1): Downloading (100%)         
  - Updating phpunit/php-file-iterator (2.0.2 => 3.0.5): Downloading (100%)       - Updating theseer/tokenizer (1.1.3 => 1.2.0): Downloading (100%)         
  - Installing sebastian/lines-of-code (1.0.3): Downloading (100%)         
  - Installing sebastian/complexity (2.0.2): Downloading (100%)         
  - Updating sebastian/code-unit-reverse-lookup (1.0.1 => 2.0.3): Downloading (100%)         
  - Updating phpunit/php-code-coverage (7.0.10 => 9.2.5): Downloading (100%)      - Updating doctrine/instantiator (1.3.0 => 1.4.0):Downloading (100%)         )
  - Updating phpspec/prophecy (v1.10.3 => 1.12.2): Downloading (100%)         
  - Updating phar-io/version (2.0.1 => 3.0.4): Downloading (100%)         
  - Updating phar-io/manifest (1.0.3 => 2.0.1): Downloading (100%)         
  - Updating myclabs/deep-copy (1.9.5 => 1.10.2): Downloading (100%)         
  - Updating phpunit/phpunit (8.5.3 => 9.5.0): Downloading (100%)         
  - Installing pclzip/pclzip (2.8.2): Downloading (100%)         
  - Installing zendframework/zend-escaper (2.6.1): Downloading (100%)         
  - Installing phpoffice/common (0.2.9): Downloading (100%)         
  - Installing phpoffice/phpword (0.17.0): Downloading (100%)         
symfony/polyfill-intl-normalizer suggests installing ext-intl (For best performance)
symfony/http-client-contracts suggests installing symfony/http-client-implementation
symfony/polyfill-intl-grapheme suggests installing ext-intl (For best performance)
phpoffice/phpword suggests installing dompdf/dompdf (Allows writing PDF)
phpoffice/phpword suggests installing ext-gd2 (Allows adding images)
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.

pi@raspberrypi:/var/www/html/phpipf $ php artisan migrate
Migrating: 2020_06_23_200200_remove_parent_filed_deps
Migrated:  2020_06_23_200200_remove_parent_filed_deps (3,267.71ms)
Migrating: 2020_07_29_190800_fix_insert_recurring_renewals
Migrated:  2020_07_29_190800_fix_insert_recurring_renewals (93.59ms)
Migrating: 2020_07_30_091000_update_special_countries
Migrated:  2020_07_30_091000_update_special_countries (1,529.77ms)
Migrating: 2020_09_18_135000_update_tables11
Migrated:  2020_09_18_135000_update_tables11 (6,458.04ms)
Migrating: 2020_10_01_130832_update_category_provisional

   Illuminate\Database\QueryException 

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`phpipf`.`matter`, CONSTRAINT `matter_type_code_foreign` FOREIGN KEY (`type_code`) REFERENCES `matter_type` (`code`) ON DELETE SET NULL ON UPDATE CASCADE) (SQL: update `matter` set `category_code` = PAT, `type_code` = PRO where `category_code` = PRO)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

      +10 vendor frames 
  11  database/migrations/2020_10_01_130832_update_category_provisional.php:14
      Illuminate\Database\Query\Builder::update(["PAT", "PRO"])

      +21 vendor frames 
  33  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
pi@raspberrypi:/var/www/html/phpipf $

**Comment by jjdejong** [comment]
Yes, the "Provisional" type probably doesn't exist in your matter_type table. That was forgotten. I've updated the "update_category_provisional" migration script. Pull the new code, do a `php artisan migrate:rollback` and again `php artisan migrate`.

**Comment by alexandreIP** [comment]
Perfect, thank you !

pi@raspberrypi:/var/www/html/phpipf $ git pull
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Dépaquetage des objets: 100% (7/7), fait.
Depuis https://github.com/jjdejong/phpip
   95d6a98..6d5336a  master     -> origin/master
Mise à jour 95d6a98..6d5336a
Fast-forward
 database/migrations/2020_10_01_130832_update_category_provisional.php | 1 +
 database/seeders/MatterTypeTableSeeder.php                            | 9 +++++++++
 2 files changed, 10 insertions(+)
pi@raspberrypi:/var/www/html/phpipf $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
pi@raspberrypi:/var/www/html/phpipf $ php artisan migrate:rollback
Rolling back: 2020_09_18_135000_update_tables11
Rolled back:  2020_09_18_135000_update_tables11 (5,345.99ms)
Rolling back: 2020_07_30_091000_update_special_countries
Rolled back:  2020_07_30_091000_update_special_countries (0.17ms)
Rolling back: 2020_07_29_190800_fix_insert_recurring_renewals
Rolled back:  2020_07_29_190800_fix_insert_recurring_renewals (0.16ms)
Rolling back: 2020_06_23_200200_remove_parent_filed_deps
Rolled back:  2020_06_23_200200_remove_parent_filed_deps (0.17ms)
pi@raspberrypi:/var/www/html/phpipf $ php artisan migrate
Migrating: 2020_06_23_200200_remove_parent_filed_deps
Migrated:  2020_06_23_200200_remove_parent_filed_deps (3,582.86ms)
Migrating: 2020_07_29_190800_fix_insert_recurring_renewals
Migrated:  2020_07_29_190800_fix_insert_recurring_renewals (78.11ms)
Migrating: 2020_07_30_091000_update_special_countries
Migrated:  2020_07_30_091000_update_special_countries (91.19ms)
Migrating: 2020_09_18_135000_update_tables11
Migrated:  2020_09_18_135000_update_tables11 (9,140.20ms)
Migrating: 2020_10_01_130832_update_category_provisional
Migrated:  2020_10_01_130832_update_category_provisional (309.41ms)
Migrating: 2020_12_04_133640_update_matter_alt_ref
Migrated:  2020_12_04_133640_update_matter_alt_ref (2,751.31ms)
pi@raspberrypi:/var/www/html/phpipf $
