### ISSUE TITLE
conversion de v1 vers v2

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#7]
Bonjour,
j'essaie de tester la version 2 après avoir suivi le wiki.
J'ai au passage une erreur de conversion du SQL, la requête suivante ne s'executant pas.
Je précise que j'avais executé tous les "patch" sql sur la version v1.
ALTER TABLE `actor`
ADD COLUMN `remember_token` VARCHAR(100) DEFAULT NULL AFTER `updater`

#1060 - Nom du champ 'remember_token' déjà utilisé

Je n'arrive pas à passer l'étape du "login" avec la nouvelle version.
Voici l'erreur:
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `actor` where `login` = alexandre limit 1)
Previous exceptions
SQLSTATE[HY000] [2002] Connection refused (2002)
SQLSTATE[HY000] [2002] Connection refused (2002)

J'ai pourtant bien un utilisateur alexandre et j'ai utilisé la commande php -r 'echo password_hash("your password",PASSWORD_BCRYPT) . "\n";' pour inscrire le résultat dans le champ mot de passe de la table acteur...

**Comment by papoteur-mga** [comment]
Bonjour Alexandre,
La question est d'abord celle de la configuration de l'accès à la base de données. Il faut prendre  le fichier .env.example le modifier et l'enregistrer sous le nom .env

**Comment by alexandreIP** [comment]
Bonjour Jean-Jacques,

j'ai bien copie et renommé le fichier en .env et modifié trois lignes:

DB_DATABASE=phpip

DB_USERNAME=phpUserNew

DB_PASSWORD=***


Je remarque qu'il n'y a pas de " " par rapport au fichier de conf de la
version 1, est ce bien cela ?

Par ailleurs, le DB_PASSWORD est dans sa version non "hachée" en "clair".
Est-ce correct ?

**Comment by jjdejong** [comment]
C'est Papoteur qui avait répondu !
Ton .env semble correct, mot de passe en clair. 
Quelques éléments en vrac : 
Est-ce que tu peux accéder à la base phpip avec l'utilisateur phpNewUser, et cet utilisateur a-t-il tous les droits sur la base phpip ?
As-tu appliqué la commande php avec le mot de passe en clair de l'utilisateur alexandre ?
As-tu bien enlevé le "salt" de la v1 au mot de passe en clair ?

**Comment by jjdejong** [comment]
Il faut par ailleurs appliquer d'autres mises à jour des tables - étape ajoutée au Wiki : 
* Apply further updates to the tables by running the "xxx_update_tables.php" migration scripts - to do this, go in the `/database/migrations` folder, move all the scripts except the "xxx_update_tables.php" scripts out of the folder, and run `php artisan migrate`from the root folder. You may want to restore the `/database/migrations` folder to its original state afterwards for pulling later updates without confusing git.

**Comment by alexandreIP** [comment]
Bonjour Jean-Jacques,,

oui phpUserNew peut accéder à la base phpip comme le montrent les lignes à
la fin du mail.

je vérifie pour la question qui suit.

Je ne suis pas sur de comprendre la dernière ligne, je reviens avec du
contenu précis.

Merci

Alexandre



IPT-ADE:~ alexandredelye$ /Applications/MAMP/Library/bin/mysql -u
phpUserNew --password=***

Warning: Using a password on the command line interface can be insecure.

Welcome to the MySQL monitor.  Commands end with ; or \g.

Your MySQL connection id is 492

Server version: 5.6.35 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input
statement.

mysql> show grants;

+------------------------------------------------------------------------+

| Grants for phpUserNew@%                                                |

+------------------------------------------------------------------------+

| GRANT USAGE ON *.* TO 'phpUserNew'@'%' IDENTIFIED BY PASSWORD <secret> |

| GRANT ALL PRIVILEGES ON `phpip`.* TO 'phpUserNew'@'%'                  |

| GRANT ALL PRIVILEGES ON `phpusernew\_%`.* TO 'phpUserNew'@'%'          |

+------------------------------------------------------------------------+

3 rows in set (0,01 sec)

**Comment by jjdejong** [comment]
La ligne `GRANT ALL PRIVILEGES ON phpusernew\_%.* TO 'phpUserNew'@'%' ` signifie que l'utilisateur phpUserNew a tous les privilèges sur les schémas commençant par phpusernew_

Sinon, as-tu vérifié que tu as lancé la commande php avec le mot de passe en clair de la v1 et non sur le hash stocké dans `actor.password` ? As-tu bien copié le hash généré par la commande php sans espace à la fin ou autre caractère ? (Des fois le hash contient des caractères qui perturbent le copier-coller, dans ce cas il vaut mieux en générer un autre - chaque exécution génère un hash valide différent)

**Comment by alexandreIP** [comment]
Bonjour Jean Jacques,

pas rapport à cet email, il est à noter que lorsque j'applique
l'instruction:

*Upgrade the phpipv2 schema with the script provided in /database/migrations/sql.*

J'obtiens l'erreur suivante:

*L'importation a réussi, 43 requêtes exécutées. (phpip-upgrade_to_v2.sql)*

Erreur

*Requête SQL :*

ALTER TABLE matter
ADD COLUMN suffix VARCHAR(16) AS ( CONCAT_WS('', CONCAT_WS('-',
CONCAT_WS('/', country, origin), type_code), idx) ) AFTER idx

*MySQL a répondu :*

#1064 - Erreur de syntaxe près de 'AS ( CONCAT_WS('', CONCAT_WS('-',
CONCAT_WS('/', country, origin), type_code), i' à la ligne 2

*Lorsqu'on l'applique une deuxième fois, on a le résultat suivant:*

*L'importation a réussi, 43 requêtes exécutées. (phpip-upgrade_to_v2.sql)*
Erreur

*Requête SQL :*

ALTER TABLE `actor`
ADD COLUMN `remember_token` VARCHAR(100) DEFAULT NULL AFTER `updater`

*MySQL a répondu :*

*#1060 - Nom du champ 'remember_token' déjà utilisé*

*Est ce que l'utilisateur phpipuser créé pour la v1 est encore utile pourla v2 ?*

Je poursuis...

Merci
Alexandre

**Comment by alexandreIP** [comment]
Pour créé l'utilisateur alexandrenew je n'ai pas encore appliqué les the "xxx_update_tables.php" migration scripts (vu les erreurs quand j'applique Upgrade the phpipv2 schema with the script provided in /database/migrations/sql.)

pour le moment je ne peux pas lui affecter le default role DBA (via
l'interface phpmyadmin, ce n'est pas proposé)

Voici le mot de passe en clair: <secret>

IPT-ADE:~ alexandredelye$ php -r 'echo
password_hash("<secret>",PASSWORD_BCRYPT) . "\n";'

$2y$10$.dJvPC1pcD/VQhBCQFKAR.sE15JZtFSSpx2E7FG8tlXyn/C7VD.8W

J'ai noté le mot de
passe $2y$10$.dJvPC1pcD/VQhBCQFKAR.sE15JZtFSSpx2E7FG8tlXyn/C7VD.8W dans le
champs password.


INSERT INTO `actor` (`ID`, `name`, `first_name`, `display_name`, `login`,
`password`, `password_salt`, `last_login`, `default_role`, `function`,
`parent_ID`, `company_ID`, `site_ID`, `phy_person`, `nationality`,
`small_entity`, `address`, `country`, `address_mailing`, `country_mailing`,
`address_billing`, `country_billing`, `email`, `phone`, `legal_form`,
`registration_no`, `warn`, `notes`, `VAT_number`, `creator`, `updated`,
`updater`, `remember_token`) VALUES
 (NULL, 'Delye', 'Alexandre', 'AlexandreNew', 'alexandrenew',
'$2y$10$.dJvPC1pcD/VQhBCQFKAR.sE15JZtFSSpx2E7FG8tlXyn/C7VD.8W',
'salt', '2019-10-20
21:50:22', NULL, NULL, NULL, NULL, NULL, '1', NULL, '0', '', NULL, '', NULL,
 '', NULL, 'root@localhost', NULL, NULL, NULL, '0', NULL, NULL,
'root', '2019-10-20
21:50:22', 'phpipUserOld', NULL);

J'ai supprimé la dernière ligne de permission de l'utilisateur phpUserNew,
voici le nouveau résultat

IPT-ADE:~ alexandredelye$ /Applications/MAMP/Library/bin/mysql -u
phpUserNew --password=***

Warning: Using a password on the command line interface can be insecure.

Welcome to the MySQL monitor.  Commands end with ; or \g.

Your MySQL connection id is 673

Server version: 5.6.35 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input
statement.

mysql> show grants;

+------------------------------------------------------------------------+

| Grants for phpUserNew@%                                                |

+------------------------------------------------------------------------+

| GRANT USAGE ON *.* TO 'phpUserNew'@'%' IDENTIFIED BY PASSWORD <secret> |

| GRANT ALL PRIVILEGES ON `phpip`.* TO 'phpUserNew'@'%'                  |

+------------------------------------------------------------------------+

2 rows in set (0,00 sec)


mysql> SELECT * FROM phpip.actor WHERE id=197;

+-----+-------+------------+--------------+--------------+--------------------------------------------------------------+---------------+---------------------+--------------+----------+-----------+------------+---------+------------+-------------+--------------+---------+---------+-----------------+-----------------+-----------------+-----------------+----------------+-------+------------+-----------------+------+-------+------------+---------+---------------------+--------------+----------------+

| ID  | name  | first_name | display_name | login        | password
                                            | password_salt | last_login
      | default_role | function | parent_ID | company_ID | site_ID |
phy_person | nationality | small_entity | address | country |
address_mailing | country_mailing | address_billing | country_billing |
email          | phone | legal_form | registration_no | warn | notes |
VAT_number | creator | updated             | updater      | remember_token |

+-----+-------+------------+--------------+--------------+--------------------------------------------------------------+---------------+---------------------+--------------+----------+-----------+------------+---------+------------+-------------+--------------+---------+---------+-----------------+-----------------+-----------------+-----------------+----------------+-------+------------+-----------------+------+-------+------------+---------+---------------------+--------------+----------------+

| 197 | Delye | Alexandre  | AlexandreNew | alexandrenew |
$2y$10$.dJvPC1pcD/VQhBCQFKAR.sE15JZtFSSpx2E7FG8tlXyn/C7VD.8W | salt
  | 2019-10-20 21:50:22 | NULL         | NULL     |      NULL |       NULL |
  NULL |          1 | NULL        |            0 |         | NULL    |
            | NULL            |                 | NULL            |
root@localhost | NULL  | NULL       | NULL            |    0 | NULL  | NULL
    | root    | 2019-10-20 21:50:22 | phpipUserOld | NULL           |

+-----+-------+------------+--------------+--------------+--------------------------------------------------------------+---------------+---------------------+--------------+----------+-----------+------------+---------+------------+-------------+--------------+---------+---------+-----------------+-----------------+-----------------+-----------------+----------------+-------+------------+-----------------+------+-------+------------+---------+---------------------+--------------+----------------+

1 row in set (0,00 sec)

Est ce correct ?

**Comment by jjdejong** [comment]
Ah, MySQL 5.6, je comprends - il faut la version 5.7 mini, qui prévoit des colonnes "calculées", d'où l'erreur en créant la colonne `suffix`.

J'ai lancé les script sql chez moi sur une base fraîchement copiée de la v1, et il marche sans erreurs.

Ta procédure de mise à jour du mot de passe semble correcte...

**Comment by alexandreIP** [comment]
Bonjour,

je suis passé à la version 5.7.26.

j'ai toujours l'erreur à la connexion depuis l'interface:

Illuminate \ Database \ QueryException (2002)
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `actor` where
`login` = alexandre limit 1)

pourtant, en ligne de commande, cela marche correctement avec l'utilisateur
phpUserNew qui est dans le fichier .env comme le montre le copier collé
ci-dessous.

Je remarque qu'il n'y a pas de "*guillemet*" autour du *alexandre* dans la
requête affichée... ?
Est ce normal ?

IPT-ADE:phpipv2 alexandredelye$ /Applications/MAMP/Library/bin/mysql -u
phpUserNew -p

Enter password:

Welcome to the MySQL monitor.  Commands end with ; or \g.

Your MySQL connection id is 92

Server version: 5.7.26 MySQL Community Server (GPL)


Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.


Oracle is a registered trademark of Oracle Corporation and/or its

affiliates. Other names may be trademarks of their respective

owners.


Type 'help;' or '\h' for help. Type '\c' to clear the current input
statement.


mysql> use phpip;

   Reading
table information for completion of table and column names

You can turn off this feature to get a quicker startup with -A


Database changed

mysql> select * from `actor` where `login` = 'alexandre' limit 1;

+-----+-------+------------+--------------+-----------+--------------------------------------------------------------+---------------+---------------------+--------------+----------+-----------+------------+---------+------------+-------------+--------------+---------+---------+-----------------+-----------------+-----------------+-----------------+----------------+-------+------------+-----------------+------+-------+------------+---------+---------------------+---------+----------------+

| ID  | name  | first_name | display_name | login     | password
                                          | password_salt | last_login
    | default_role | function | parent_ID | company_ID | site_ID |
phy_person | nationality | small_entity | address | country |
address_mailing | country_mailing | address_billing | country_billing |
email          | phone | legal_form | registration_no | warn | notes |
VAT_number | creator | updated             | updater | remember_token |

+-----+-------+------------+--------------+-----------+--------------------------------------------------------------+---------------+---------------------+--------------+----------+-----------+------------+---------+------------+-------------+--------------+---------+---------+-----------------+-----------------+-----------------+-----------------+----------------+-------+------------+-----------------+------+-------+------------+---------+---------------------+---------+----------------+

| 121 | Delye | Alexandre  | Alexandre    | alexandre |
$2y$10$ojdbs6LUheg0Uwo6lNSc8OqHSrYvm2E7PnBtBmvQptPH.wrQaWw5S |
  | 2019-10-20 21:50:22 | NULL         | NULL     |      NULL |       NULL |
  NULL |          1 | NULL        |            0 |         | NULL    |
            | NULL            |                 | NULL            |
root@localhost | NULL  | NULL       | NULL            |    0 | NULL  | NULL
    | root    | 2019-11-01 18:09:25 | root2   | NULL           |

+-----+-------+------------+--------------+-----------+--------------------------------------------------------------+---------------+---------------------+--------------+----------+-----------+------------+---------+------------+-------------+--------------+---------+---------+-----------------+-----------------+-----------------+-----------------+----------------+-------+------------+-----------------+------+-------+------------+---------+---------------------+---------+----------------+

1 row in set (0,00 sec)


mysql>

Le lun. 21 oct. 2019 à 15:31, Jean J. de Jong <notifications@github.com> a
écrit :

**Comment by alexandreIP** [comment]
a nouveau bonsoir, quelques éléments supplémentaires:

la migration avec /database/migrations/sql
s'est bien passée.


Je n'avais pas lancé la commande php artisan migrate

quand j'essaie la commande php artisan migrate, j'ai:


IPT-ADE:phpipv2 alexandredelye$ php artisan migrate


  * Illuminate\Database\QueryException * : SQLSTATE[HY000] [2002]
Connection refused (SQL: select * from information_schema.tables where
table_schema = phpip and table_name = migrations and table_type = 'BASE
TABLE')


  at
/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:664

    *660| *        *// If an exception occurs when attempting to run a
query, we'll format the error*

    *661|         // message to include the bindings with SQL, which will
make this exception a*

    *662|         // lot more helpful to the developer instead of just the
database's errors.*

    *663|         *catch (*Exception $e*) {

*  > **664| *            throw new *QueryException*(

    *665| *                *$query*, *$this*->*prepareBindings*(*$bindings*),
*$e*

    *666| *            );

    *667| *        }

    *668| *


  Exception trace:


  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002]
Connection refused")


/Applications/MAMP/htdocs/phpipv2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
:31


  2   PDOException::("SQLSTATE[HY000] [2002] Connection refused")


/Applications/MAMP/htdocs/phpipv2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
:27


  Please use the argument -v to see more details.




et en mode verbose:


IPT-ADE:phpipv2 alexandredelye$ php artisan migrate -v


  * Illuminate\Database\QueryException * : SQLSTATE[HY000] [2002]
Connection refused (SQL: select * from information_schema.tables where
table_schema = phpip and table_name = migrations and table_type = 'BASE
TABLE')


  at
/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:664

    *660| *        *// If an exception occurs when attempting to run a
query, we'll format the error*

    *661|         // message to include the bindings with SQL, which will
make this exception a*

    *662|         // lot more helpful to the developer instead of just the
database's errors.*

    *663|         *catch (*Exception $e*) {

*  > **664| *            throw new *QueryException*(

    *665| *                *$query*, *$this*->*prepareBindings*(*$bindings*),
*$e*

    *666| *            );

    *667| *        }

    *668| *


  Exception trace:


  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002]
Connection refused")


/Applications/MAMP/htdocs/phpipv2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
:31


  2   PDOException::("SQLSTATE[HY000] [2002] Connection refused")


/Applications/MAMP/htdocs/phpipv2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
:27


  3   PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=phpip",
"phpUserNew", "1YxxnV2mFRcWENni", [])


/Applications/MAMP/htdocs/phpipv2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
:27


  4   Doctrine\DBAL\Driver\PDOConnection::__construct("mysql:host=127.0.0.1;port=3306;dbname=phpip",
"phpUserNew", "1YxxnV2mFRcWENni", [])


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php
:67


  5   Illuminate\Database\Connectors\Connector::createPdoConnection("mysql:host=127.0.0.1;port=3306;dbname=phpip",
"phpUserNew", "1YxxnV2mFRcWENni", [])


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php
:46


  6   Illuminate\Database\Connectors\Connector::createConnection("mysql:host=127.0.0.1;port=3306;dbname=phpip",
[])


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php
:24


  7   Illuminate\Database\Connectors\MySqlConnector::connect()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php
:182


  8
Illuminate\Database\Connectors\ConnectionFactory::Illuminate\Database\Connectors\{closure}()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:919


  9   call_user_func(Object(Closure))


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:919


  10  Illuminate\Database\Connection::getPdo()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:944


  11  Illuminate\Database\Connection::getReadPdo()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:399


  12  Illuminate\Database\Connection::getPdoForSelect()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:325


  13  Illuminate\Database\Connection::Illuminate\Database\{closure}("select
* from information_schema.tables where table_schema = ? and table_name = ?
and table_type = 'BASE TABLE'")


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:657


  14  Illuminate\Database\Connection::runQueryCallback("select * from
information_schema.tables where table_schema = ? and table_name = ? and
table_type = 'BASE TABLE'", Object(Closure))


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:624


  15  Illuminate\Database\Connection::run("select * from
information_schema.tables where table_schema = ? and table_name = ? and
table_type = 'BASE TABLE'", Object(Closure))


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Connection.php
:333


  16  Illuminate\Database\Connection::select("select * from
information_schema.tables where table_schema = ? and table_name = ? and
table_type = 'BASE TABLE'")


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php
:18


  17  Illuminate\Database\Schema\MySqlBuilder::hasTable("migrations")


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php
:169


  18
Illuminate\Database\Migrations\DatabaseMigrationRepository::repositoryExists()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php
:585


  19  Illuminate\Database\Migrations\Migrator::repositoryExists()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php
:91


  20
Illuminate\Database\Console\Migrations\MigrateCommand::prepareDatabase()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php
:63


  21  Illuminate\Database\Console\Migrations\MigrateCommand::handle()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
:32


  22  call_user_func_array([])


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
:32


  23  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
:90


  24  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application),
Object(Closure))


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
:34


  25  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application),
[])


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Container/Container.php
:576


  26  Illuminate\Container\Container::call()


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Console/Command.php
:183


  27  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Illuminate\Console\OutputStyle))


/Applications/MAMP/htdocs/phpipv2/vendor/symfony/console/Command/Command.php
:255


  28  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Illuminate\Console\OutputStyle))


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Console/Command.php
:170


  29  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))


/Applications/MAMP/htdocs/phpipv2/vendor/symfony/console/Application.php:921


  30  Symfony\Component\Console\Application::doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand),
Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))


/Applications/MAMP/htdocs/phpipv2/vendor/symfony/console/Application.php:273


  31  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))


/Applications/MAMP/htdocs/phpipv2/vendor/symfony/console/Application.php:149


  32  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Console/Application.php
:90


  33  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))


/Applications/MAMP/htdocs/phpipv2/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php
:133


  34  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))

      /Applications/MAMP/htdocs/phpipv2/artisan:37

IPT-ADE:phpipv2 alexandredelye$

**Comment by papoteur-mga** [comment]
Bonsoir Alexandre,
D'abord, si tu as migré depuis la V1, il ne faut pas lancer php artisan migrate : la fonction de cette commande est de créer toutes les tables, vues et autres déclencheurs. Ils existent déjà.
Mais le résultat montre toujours le même problème : tu accèdes à la base, mais tu n'as pas les droits pour y lire des choses.
Si tu as toujours l'utilisateur root, tu peux essyer avec, au moins pour voir.
Est-ce que tous les serveurs sont sur la même machine ? Mysql fait la distinction entre les utitlisateurs selon qu'ils proviennent de la même machine ou d'une autre sur le même réseau, ou encore par Internet.

**Comment by alexandreIP** [comment]
Bonjour Jean-Jacques,

j'avais compris qu'il fallait le faire car sous le chapeau "Migrate the v1
database", il y a l'étape:
Copy the phpip MySQL schema to a new one (say phpipv2).
Upgrade the phpipv2 schema with the script provided in
/database/migrations/sql.
Apply further updates to the tables by running the "xxx_update_tables.php"
migration scripts - to do this, go in the /database/migrations folder, move
all the scripts except the "xxx_update_tables.php" scripts out of the
folder, and *run php artisan migrate *from the root folder. You may want to
restore the /database/migrations folder to its original state afterwards
for pulling later updates without confusing git.

Alexandre

**Comment by alexandreIP** [comment]
Bonjour Jean-Jacques

"victoire".... c'était le port de la base mysql qu'il fallait changé.
J'utilise MAMP pour lequel le port de MySql n'est pas le classique;

Je vois donc maintenant le tableau principal.

Cepandant, j'ai une erreur pour à peu près chaque action:
"Internal Server Error
The server encountered an internal error or misconfiguration and was unable
to complete your request.

Please contact the server administrator, you@example.com and inform them of
the time the error occurred, and anything you might have done that may have
caused the error.

More information about this error may be available in the server error log."

J'investigue...

Alexandre

**Comment by alexandreIP** [comment]
J'ai le même type d'erreur avec une base nouvelle créée avec :
php artisan migrate --seed
"Internal Server Error The server encountered an internal error or
misconfiguration and was unable to complete your request. Please contact
the server administrator, you@example.com and inform them of the time the
error occurred, and anything you might have done that may have caused the
error. More information about this error may be available in the server
error log."

**Comment by papoteur-mga** [comment]
Bonjour Alexandre,
Il faut pouvoir obtenir plus de détail sur l'erreur.
Pour cela, en général, j'active la console "Firebug" de Firefox, lance la page qui provoque l'erreur, choisis l'onglet "Réseau" sur la partie gauche et "Réponse" sur la partie droite.
Sinon, il faut trouver où sont les fichiers historiques genre error_log.
Si tu as configuré le Virtualhost, le fichier d'enregistrement des erreurs y est défini.

**Comment by alexandreIP** [comment]
Bonsoir
est obligatoire d'avoir un virtualhost: avec mamp ca n'est pas "aisé".
firebug de firefox ne semble plus être maintenue. Je vais le télécharger.

**Comment by papoteur-mga** [comment]
Quand je disais Firebug, c'est pour désigner l'outil de débogage.
https://developer.mozilla.org/fr/docs/Outils/D%C3%A9bogueur/Comment/Ouvrir_le_d%C3%A9bogueur
Il n'y a rien à installer.
Le virtualhost permet de désigner le point d'entrée dans l'arborescence des fichiers. Je n'ai jamais essayé sans.

**Comment by papoteur-mga** [comment]
Peut être ici ?
https://stackoverflow.com/questions/35251032/how-to-create-virtual-hosts-in-mamp

**Comment by jjdejong** [comment]
> Bonsoir est obligatoire d'avoir un virtualhost: avec mamp ca n'est pas "aisé". firebug de firefox ne semble plus être maintenue. Je vais le télécharger.

**Comment by jjdejong** [comment]
C'est obligatoire. Mais avant, tu peux tout tester avec la commande 'php artisan serve' lancée dans le répertoire racine

**Comment by alexandreIP** [comment]
Bonjour,

avec une base vide puis remplie avec
php artisan migrate -- seed
php artisan db:seed --class=SampleSeeder

et en utilisant php artisan serve

je n'arive pas à créer un dossier brevet : the given data was invalid
[image: image.png]

Idem, je n'arrive pas à cloner un dossier brevet

Le dim. 3 nov. 2019 à 00:23, Jean J. de Jong <notifications@github.com> a
écrit :

**Comment by papoteur-mga** [comment]
Bonjour,
Par quelle voie la création est-elle faite ?
Dans les champs qui sont à "autocomplémentation", il faut sélectionner l'élément qui est affiché dans la lsite qui est affichée dynamiquement sous le champ. Par exemple, dans le champ "Category", si on saisi "pat", "Patent" s'affiche en dessous et il faut le sélectionner.

**Comment by alexandreIP** [comment]
Jamais créé en utilisant les scripts.
J’ai bien sélectionné la proposition Patent après avoir écrit Pat
Mais je n ai pas encore le virtual host c est en restant avec artisan serve

(Le clonage ne fonctionne pas non plus et retourne une erreur)

**Comment by papoteur-mga** [comment]
Je n'ai pas l'image. Quel champ est encadré en rouge ?
Je ne pense pas que la manière dont le serveur fonctionne influence cette partie.

**Comment by alexandreIP** [comment]
Les deux premiers champs sont encadrés en rouge.

**Comment by papoteur-mga** [comment]
C'est avec quel navigateur ?
Nous avons fait nos essais uniquement avec Firefox.

**Comment by alexandreIP** [comment]
effectivement, j'étais sous chrome.
en passant sur firefox, et en ayant réussi à faire fonctionner le virtual
host (au passage , il ne faut pas mettre de guillemets pour indiquer le
répertoire contrairement à ce que dit sur le site
https://stackoverflow.com/questions/35251032/how-to-create-virtual-hosts-in-mamp,
cela finit par fonctionner sur Firefox !
Mais pas sur Chrome...

**Comment by papoteur-mga** [comment]
Bien.
Au passage, j'ai repéré une erreur quand on crée un nouveau dossier depuis le cadre des catégories, au niveau d'une rangée.
Je vais tenter de corriger.

**Comment by alexandreIP** [comment]
pouvez vous me confirmer qu'il ne FAUT PAS faire l'étape 3:

   - Copy the phpip MySQL schema to a new one (say phpipv2).
   - Upgrade the phpipv2 schema with the script provided in
   /database/migrations/sql.
   - Apply further updates to the tables by running the
   "xxx_update_tables.php" migration scripts - to do this, go in the
   /database/migrations folder, move all the scripts except the
   "xxx_update_tables.php" scripts out of the folder, and run php artisan
   migratefrom the root folder. You may want to restore the
   /database/migrations folder to its original state afterwards for pulling
   later updates without confusing git.

que dois mettre dans default_role ?

je peux voir tous les enregistrement, mais pas les modifier ni en ajouter.

**Comment by papoteur-mga** [comment]
On parle de migration d'une base qui était en version v1 ?
Dans ce cas, si, il faut appliquer aussi cette migration. Sinon, le script est déjà appliqué. Attention, c'est le seul script qui doit rester dans le répartoire database/migrations au moment d'exécuter la commande.

**Comment by alexandreIP** [comment]
Merci
Maintenant ca fonctionne parfaitement!

**Comment by jjdejong** [comment]
Le problème semble réglé donc.
