### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by timowevel1** [jjdejong/phpip#74]
Hello,

I got everything deployed now, is there a default admin login? Or how can I create an account?

Thanks.

**Comment by jjdejong** [comment]
Did you read the documentation a little? One user is created by default, and that user has admin rights.
https://github.com/jjdejong/phpip/wiki/2.-Installing#31-starting-a-new-database

User management is not very sophisticated. Once connected, you can manage users through Tables->DB Users. "DB Users" are a subset of "Actors": any actor becomes a DB User by providing a login through Tables->Actors
