### ISSUE TITLE
Renewal log page causes server error

### ISSUE THREAD

**Issue by jjdejong** [jjdejong/phpip#78]
ERROR: Trying to get property 'matter' of non-object (View: /var/www/phpip_prod/resources/views/renewals/logs.blade.php) {"view":{"view":"/var/www/phpip_prod/resources/views/renewals/logs.blade.php"

**Comment by papoteur-mga** [comment]
Salut Jean-Jacques. Hum, je ne reproduis pas. Comment cette erreur arrive-t-elle ?

**Comment by jjdejong** [comment]
En cliquant tout simplement sur le bouton "view logs".

**Comment by papoteur-mga** [comment]
Closed with fd0b58a
