### ISSUE TITLE
Reset password form -- not sending password in .env

### ISSUE THREAD

**Issue by srdco** [jjdejong/phpip#9]
Ubuntu 18.04, PHP7.3, PHPIP-V2 (fresh install)

When trying to use the 'reset password' form to send email using SMTP, I get:
```
 Swift_TransportException
Connection could not be established with host email.solidrock.enterprises [Connection refused #111]
```

The email server maillog shows:
```
email postfix/submission/smtpd[26492]: connect from mywebdomain.com[web-ip-address]
email postfix/submission/smtpd[26492]: Anonymous TLS connection established from mywebdomain.com[web-ip-address]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
email postfix/submission/smtpd[26492]: warning:mywebdomain.com[web-ip-address]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
```

UGFzc3dvcmQ6 resolves to "password" (see https://serverfault.com/questions/211631/sasl-login-authentication-failed-ugfzc3dvcmq6-find-the-username). Thus ... it appears that SwiftMail is just sending "password", and not the password setup in my .env file.

For reference, the mail portion of the .env file for PHPIP-V2 is:
MAIL_DRIVER=smtp
MAIL_HOST=myemailserver.com
MAIL_PORT=587
MAIL_USERNAME=user@mywebdomain.com
MAIL_PASSWORD=myemailpassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=user@mywebdomain.com
MAIL_FROM_NAME="user@mywebdomain.com"

Is this an error that should be fixed, or a configuration issue? Not being familiar with Laravel, I am hesitant to go mucking in the code without a second opinion.

**Comment by srdco** [comment]
ALSO ... is there a way to create a new user/password beside adding an actor with a login, and then using the reset password form?

**Comment by srdco** [comment]
UPDATE: Just tried changing email host from my primary email (on another internally-managed server) to a secondary gmail account.
Was able to successfully send password reset.
Therefore, it looks like this is a configuration problem, not a bug.
Before I close this ... any ideas?

**Comment by srdco** [comment]
Worked at it some more. Successful now. It appears that (at least for my email server), it needed the MAIL_FROM_ADDRESS, but NOT the MAIL_FROM_NAME. See working portion of .env file below:
```
MAIL_DRIVER=smtp
MAIL_HOST=myemailserver.com
MAIL_PORT=587
MAIL_USERNAME=user@mywebdomain.com
MAIL_PASSWORD=myemailpassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=user@mywebdomain.com
```

Thanks!

**Comment by papoteur-mga** [comment]
Hello,
Thanks for the report.
For my development environment, I just used sendmail.
